CherryHQ/cherry-studio

- README.ja.md
- README.zh.md
I created Japanese translated README.
> docs: add Japanese README file

- src/main/ipc.ts
- src/main/services/ConfigManager.ts
- src/main/utils/locales.ts
- src/main/window.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/GeneralSettings.tsx
- src/renderer/src/store/settings.ts
- src/renderer/src/types/index.ts
https://github.com/kangfenmao/cherry-studio/issues/281
Changing the application language does not affect the context menu texts
> Added locale for context-menu

- src/main/services/TrayService.ts
Issue https://github.com/kangfenmao/cherry-studio/issues/327
> fix: the context menu is not displayed on linux

- docs/README.ja.md
- docs/README.zh.md
PR updates the license reference in `docs/README.ja.md` and `docs/README.zh.md`.
> docs: update license reference

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
> style: 💄 change chinese-traditional icon to hk

- src/renderer/src/config/models.ts
Add the grok vision model 和 fix the incorrect marking of the grok beta model as a visual model.
> fix: Grok model

- src/renderer/src/assets/styles/markdown.scss
Allow markdown long text to automatically wrap.
> feat: 🎸Allow markdown long text to automatically wrap.

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/DataSettings/WebDavSettings.tsx
- src/renderer/src/services/BackupService.ts
- src/renderer/src/store/settings.ts
在 WebDav 设置界面中加入自动同步设置。具体如下：
1. 为“WebDavSettings”增添“webdavAutoSync”以及“webdavSyncInterval”，以此实现对自动同步开关的设置以及同步时间的设定。
2. 向“BackupService”中添加“startAutoSync”和“stopAutoSync”，用于切换自动同步功能。
3. 同步更新国际化（i18n）内容。
4. 添加相对应弹窗提示。
Closes #516
> [feat]: Set up automatic synchronization function for webdav

- src/renderer/src/hooks/useShortcuts.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> fix: shortcut tips

- src/renderer/src/i18n/locales/zh-tw.json
> 修复zh-tw语言文件中的乱码

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
> fix: 中文国际化错误

- src/renderer/src/pages/home/Inputbar/AttachmentPreview.tsx
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
- src/renderer/src/pages/home/Inputbar/MentionModelsInput.tsx
- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageContent.tsx
- src/renderer/src/pages/home/Messages/Messages.tsx
- src/renderer/src/types/index.ts
feat: 添加模型提及功能，支持多个模型一起回答
style: 优化附件组件显示样式
> feat: 添加模型提及功能，支持多个模型一起回答

- src/renderer/src/components/MinApp/index.tsx
现在想固定一个小程序到侧边栏，还需要关闭当前小程序然后再去小程序列表中操作，感觉太麻烦了。
给标题栏添加一个置顶按钮，觉得某个小程序好用，可以直接固定到侧边栏。
> feat: 小程序标题栏添加置顶按钮

- src/renderer/src/components/MinApp/index.tsx
> fix: 保证只有小程序才显示固定按钮

- src/renderer/src/pages/settings/AssistantSettings/AssistantMessagesSettings.tsx
> fix: 🐛 fixed bug #779

- src/renderer/src/App.tsx
- src/renderer/src/components/Popups/SettingsPopup.tsx
- src/renderer/src/components/app/Sidebar.tsx
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- src/renderer/src/pages/settings/SettingsPage.tsx
- src/renderer/src/pages/settings/index.tsx
- src/renderer/src/pages/translate/TranslatePage.tsx
refactor(settings): 重构设置页面，改为弹框
> refactor(settings): 重构设置页面，改为弹框

- package.json
- src/renderer/src/App.tsx
- src/renderer/src/components/Popups/SettingsPopup.tsx
- src/renderer/src/components/app/Sidebar.tsx
- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- src/renderer/src/pages/settings/SettingsPage.tsx
- src/renderer/src/pages/settings/index.tsx
- src/renderer/src/pages/translate/TranslatePage.tsx
- yarn.lock
> feat: optimize topics list performance with virtual list

- src/main/services/WindowService.ts
修复了在小程序中无法使用 context-menu 的问题 ～～
#864
> fix: 修复 mini-app 中无法使用 context-menu 的问题

- src/renderer/src/providers/OpenAIProvider.ts
本来准备在 UI 加上 Swich 开关控制温度的。但看到之前有对 o1, DeepSeek 的处理，就直接在这里加了
#911
> fix: OpenAI o3-mini 无法使用

- src/renderer/src/pages/home/Messages/MessageThought.tsx
- src/renderer/src/utils/formats.ts
更好的处理 \<think /\> 标签的情况，优化体验 ～
> feat: optimize MessageThought to enhance user experience

- src/renderer/src/i18n/locales/en-us.json
temperature tip's description is wrong
> fix: temperature tip English translation

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/agents/components/AddAgentPopup.tsx
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/settings/AssistantSettings/AssistantKnowledgeBaseSettings.tsx
- src/renderer/src/pages/settings/AssistantSettings/index.tsx
- src/renderer/src/types/index.ts
> feat: 不同的Agents预设不同的知识库

- src/renderer/src/providers/OpenAIProvider.ts
> fix: o3-mini markdown formatting #997

- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
- src/renderer/src/services/AssistantService.ts
1. 解决 #1158 
2. 优化模型特性默认支持的显示，在原有禁用操作的情况下加上默认勾选
> fix issue #1158 and some impove

- src/renderer/src/pages/home/Messages/MessageThought.tsx
1 目前思考过程堆积在一块，显示不美观
2 优化了效果，让上下行之间有间隙
> feat: 优化思考过程显示的换行效果

- src/renderer/src/pages/settings/ShortcutSettings.tsx
> fix: 快捷键无法绑定空格

- src/renderer/src/config/models.ts
> feat: expand web search models

- src/renderer/src/providers/OpenAIProvider.ts
参见 #1559。前端苦手，请轻喷。不知道是不是最佳解决方案。
>  fix: Translation error when passing empty user messages to certain models.

- src/renderer/src/context/SyntaxHighlighterProvider.tsx
> fix: Remove trailing newline in codeblocks

- src/renderer/src/providers/OpenAIProvider.ts
PR #1253 fixed reasoning time calculation for APIs that return reasoning content in `delta.content`, but introduced a regression for those returning it in `delta.reasoning_content`. This commit fixes the regression.
Fixes #1593
> fix: Regression on reasoning time

- src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
> feat: Improve model search by adding name-based filtering, resolve #1520

- .gitignore
> chore: 🤖 add aider gitignore

- src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
- 修复使用方向键上下移动时，列表不随之滚动的问题
- 添加滚动条
> fix: Improve the @ model list experience

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
> fix: Switching model does not work

- src/main/loader/index.ts
恢复 HTML Loader。上次我 PR 了对 HTML 类型的解析 (#1260)，但被后来的 commit 覆盖了
> fix: support html file in knowledge base

- src/renderer/src/components/Popups/MinAppsPopover.tsx
> fix: 窗口较小时，工具显示适配问题

- package.json
- packages/shared/config/constant.ts
- src/main/loader/epubLoader.ts
- src/main/loader/index.ts
- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- yarn.lock
因为有很多电子书都是 epub 格式的，所以知识库支持导入 epub 文件想必很有帮助。
> feat: Add EPUB file support to file loader

- src/renderer/src/config/minapps.ts
- src/renderer/src/pages/settings/DisplaySettings/MiniAppIconsManager.tsx
- 修复小程序拖动排序不生效的问题
- 修复小程序拖动排序时，滚动列表，排序不生效的问题
- 更正 Perplexity 小程序名字首字母未大写的问题
> fix: the miniapp sorting problem, resolve #1725

- src/renderer/src/config/models.ts
兼容谷歌的 gemini-2.0-flash-thinking-exp 系列模型
> feat: Expand reasoning model regex to include 'thinking' keyword

- src/renderer/index.html
修复 CherryStudio 标题栏标题可能变成 index.html 的问题
> feat: Add page title for Cherry Studio, resolve #1222

- src/renderer/src/pages/agents/components/AddAgentPopup.tsx
- src/renderer/src/pages/home/Inputbar/KnowledgeBaseButton.tsx
- src/renderer/src/pages/settings/AssistantSettings/AssistantKnowledgeBaseSettings.tsx
添加了知识库的筛选功能
autofocus试了很多都无法很好的实现，无法同步搜索框和下拉框的状态，后续有需要再弄吧
> feat: add knowledge base filter

- src/renderer/src/components/Popups/PromptPopup.tsx
- src/renderer/src/components/Popups/TextEditPopup.tsx
实现编辑话题名、编辑话题提示词、编辑用户已发送消息等模态弹窗激活时，自动聚焦到文本末尾
> perf: improve text input focus handling in popup components

- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageGroup.tsx
- src/renderer/src/pages/home/Messages/MessageGroupMenuBar.tsx
1. 优化消息组操作条UI问题；
2. 优化消息组横向布局时，滚动的时候固定助手头像信息；
> style: 优化聊天窗口UI

- src/renderer/src/config/models.ts
[来开放平台体验 Kimi 智能助手最新模型！](https://mp.weixin.qq.com/s/cS0DGGqUP1JOFSnzFWiqJQ)
支持月之暗面最新发布的 kimi-latest 模型
> feat: Add kimi-latest model support in vision and model logos

- src/main/services/KnowledgeService.ts
- src/renderer/src/hooks/useKnowledge.ts
- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/pages/knowledge/components/StatusIcon.tsx
效果：
https://github.com/user-attachments/assets/379289dc-cd5a-4013-9c90-40a5f49030ae
> feat: 知识库目录进度可视化

- src/renderer/src/pages/home/Messages/MessageError.tsx
- src/renderer/src/services/ApiService.ts
> fix: 解决生成过程中出现错误内容被清空覆盖问题

- src/renderer/src/config/translate.ts
- src/renderer/src/pages/translate/TranslatePage.tsx
> fix: Update language options promptly

- src/renderer/src/hooks/useModel.ts
- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageContent.tsx
> fix: update model identification with provider-specific uniqueness

- src/renderer/src/pages/translate/TranslatePage.tsx
> feature: Adaptive height of textarea on translation page

- src/renderer/src/pages/translate/TranslatePage.tsx
1. 翻译页UI重构；
2. 代码精简；
https://github.com/user-attachments/assets/4ddd2f41-662d-498b-ad47-3af1851a976e
> refactor: 翻译页UI重构

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
- src/renderer/src/store/settings.ts
- src/renderer/src/utils/export.ts
> feat: 为 Notion 导出添加可配置的页面名称 key

- src/renderer/src/pages/home/Navbar.tsx
> feat: Add model generation check before narrow mode toggle

- src/renderer/src/databases/index.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/pages/translate/TranslatePage.tsx
- src/renderer/src/types/index.ts
> feat: 添加翻译历史功能

- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/pages/knowledge/components/StatusIcon.tsx
> fix: knowledge base status problem

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Add feature: When the input box for the conversation is empty and models has been selected, pressing backspace will delete the last selected model
> feat: Add backspace handling to remove last mentioned model

- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
> feat: Add emoji selection for assistant name

- src/renderer/src/components/MinApp/index.tsx
> feat: add developer tools button in MinApp for development mode

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
> fix: Regenerat messages don't use @ specified models

- src/renderer/src/pages/knowledge/KnowledgePage.tsx
> feat: Auto-select newly added knowledge base

- src/renderer/src/pages/home/Tabs/AssistantItemComponent.tsx
- src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
fix:清空话题总是修复当前话题
Fixes https://github.com/CherryHQ/cherry-studio/issues/2107]
> fix:清空话题总是清除当前话题

- src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
- src/renderer/src/pages/knowledge/components/KnowledgeSearchPopup.tsx
- 点击“搜索知识库”后，焦点自动聚焦到输入框
- 点击“添加”创建新知识库，焦点自动聚焦到名称输入框
> feat: Enhance knowledge popup input focus behavior

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
> feat: 用户侧消息快捷重试功能

- .gitignore
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/types/index.ts
> feat: Add remark function to knowledge url

- src/main/services/KnowledgeService.ts
> fix bug: uniqueIds is null when uploaded directory

- src/renderer/src/providers/OpenAIProvider.ts
- src/renderer/src/utils/formats.ts
适配 GLM-Zero-Preview 模型的思维链输出格式
Resolve #1640
> feat: Adapt glmzeropreview thinking chain format, enhance message thought processing with flexible extractors

- src/renderer/src/config/models.ts
- feat:
- add new `claude-3-7-sonnet-20250219` claude 3.7 sonnet model support
- add `claude-3-5-haiku-20250219` claude 3.5 haiku model support
- remove invaild `claude-3-sonnet` model support
> feat: add new claude 3.7 model support

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
- src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
- src/renderer/src/store/settings.ts
- src/renderer/src/utils/export.ts
> feat: 新增导出到语雀功能

- packages/shared/config/constant.ts
https://github.com/CherryHQ/cherry-studio/issues/2287
> feat: 知识库支持更多txt based格式, 包括org, wiki, ipynb

- src/renderer/src/config/prompts.ts
> feat: Enhance reference prompt with language matching instruction

- src/renderer/src/utils/index.ts
> fix bug: 深色模式对话导出渲染不正确

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> feat: Support more file drag and drop scenarios

- src/renderer/src/utils/formats.ts
> feat: Improve think tag processing with more robust parsing

- src/renderer/src/providers/OpenAIProvider.ts
add better support for openrouter thinking format
> feat: add better support for openrouter thinking format

- .github/issues-checker.yml
- .github/workflows/issues-check.yml
使用GitHub Actions创造issues-checker逻辑
> ci: add issues checker

- src/renderer/src/components/Popups/UserPopup.tsx
根据 feature request: https://github.com/CherryHQ/cherry-studio/issues/2459
> feat: Add GIF support for avatar uploads without compression

- src/renderer/src/handler/NavigationHandler.tsx
- Add location check to prevent navigating to settings when already on settings page
- Enable hotkey on content editable and form elements
- 防止在已经位于设置页面时导航到设置
- 即使正在编辑文本也依旧打开设置页面
> feat: Improve settings navigation hotkey behavior

- src/renderer/src/providers/OpenAIProvider.ts
restore support for o1 streaming according to latest updates.
> feat: allow o1 streaming

- package.json
- src/main/ipc.ts
- src/main/services/GeminiService.ts
- src/main/services/KnowledgeService.ts
- src/main/services/ProxyManager.ts
- src/main/services/WebDav.ts
- yarn.lock
fix #1645 
fix #2284 
1. 测试WebDav 成功代理webDev请求（由于web服务器在tailnet网络，在规则中本不应该被代理，这里作为测试展示），于是报错
2. gemini：参见https://github.com/google-gemini/generative-ai-js/issues/29#issuecomment-1866246513
Gemini File API能够走代理
3. 嵌入模型：
> fix: some proxy errors in main process

- src/renderer/src/pages/home/Tabs/AssistantItem.tsx
- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
> feat: Enhance Assistant and Topic components with title attributes for better accessibility

- src/renderer/src/config/models.ts
- fix: Name typo for Claude 3.5 Haiku
> fix:Claude model name typo

- src/renderer/src/config/models.ts
feat: add `gpt-4.5-preview` support for GPT 4.5
> feat: add support for GPT 4.5

- src/renderer/src/context/ThemeProvider.tsx
- src/renderer/src/windows/mini/App.tsx
> feat: let quick assistant follow theme setting

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
> feat: Added More Settings section with risk warnings in model type configuration

- src/renderer/src/utils/formats.ts
在折叠前先判断是否为推理模型，解决包含 ###Thinking 或者 </think > 的正常内容被误识别为思维链内容导致被折叠的情况
Fix #2506
> fix: Normal content is misidentified as chain of thought content

- src/renderer/src/components/Popups/UserPopup.tsx
- src/renderer/src/components/app/Sidebar.tsx
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/home/Messages/MessageHeader.tsx
- src/renderer/src/services/ImageStorage.ts
- Implement emoji avatar detection and rendering in UserPopup, Sidebar, and MessageHeader
- Add EmojiAvatar styled components for consistent emoji display
- Update ImageStorage service to support storing emoji strings
- Introduce emoji picker functionality in UserPopup
根据 feature request: https://github.com/CherryHQ/cherry-studio/issues/2459
> feat: Add emoji avatar support across multiple components 

- src/renderer/src/services/ApiService.ts
> fix: fix bug of metrics missing

- src/main/services/WindowService.ts
1. fix: #2482 
2. Add Escape key support for exiting fullscreen mode
> fix: Fix app quit exceptionally on MacOS's full screen mode 

- src/renderer/src/config/models.ts
> fix: show correct logo for qwen-omni-turbo

- src/renderer/src/pages/settings/GeneralSettings.tsx
> feat: Save proxy setting

- src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
- src/renderer/src/pages/settings/ProviderSettings/AddModelPopup.tsx
> feat: Update model label format to include provider information

- src/main/services/ExportService.ts
fix: #2769 
原图：
导出结果
[Claude与DeepSeek R对比分析.docx](https://github.com/user-attachments/files/19076241/Claude.DeepSeek.R.docx)
> feat: support table and hyperlink when export to word

- src/renderer/src/handler/NavigationHandler.tsx
- Fix #2791 
修复「打开设置」快捷键开关处于关闭状态时，快捷键依然生效的问题
> feat: Enable conditional settings shortcut based on user preferences

- src/renderer/src/services/WebSearchService.ts
- src/renderer/src/store/websearch.ts
@kangfenmao enabled属性删除后有几个对应的地方需要删除
> fix: websearch enabled bug

- src/main/config.ts
> feat: Windows Control Overlay button hover effect

- src/main/services/mcp.ts
- src/renderer/src/providers/AnthropicProvider.ts
- src/renderer/src/providers/GeminiProvider.ts
- src/renderer/src/providers/OpenAIProvider.ts
- src/renderer/src/providers/mcpToolUtils.ts
1. support to GeminiProvider
2. support  AnthropicProvider
3. Limits: claude/gemini in AiHubMix do not supported as they do not follow Anthropic / Google
> feat(MCP): support gemini and claude models

- src/renderer/src/config/models.ts
> feat:(REGEX):  Resaoning models regex matching QWEN's qwq series models

- src/renderer/src/providers/BaseProvider.ts
add "HTTP-Referer"  and "X-Title" to defaultHeaders
> Site title for rankings on OpenRouter

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
> feat: a button to add a whole group of models

- src/renderer/src/store/websearch.ts
@kangfenmao websearch.ts仍旧有误，需要合并一下
> fix: remove duplicate property in websearch

- src/renderer/src/assets/fonts/icon-fonts/iconfont.css
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
- src/renderer/src/providers/AnthropicProvider.ts
- src/renderer/src/providers/GeminiProvider.ts
- src/renderer/src/providers/OpenAIProvider.ts
- src/renderer/src/providers/mcpToolUtils.ts
- src/renderer/src/types/index.ts
> ✨ feat(MCP): add support for enabling/disabling MCPServers per message

- src/renderer/src/components/Popups/PromptPopup.tsx
> fix(UX): Improve Enter key handling in PromptPopup input

- src/renderer/src/pages/settings/ProviderSettings/ApiCheckPopup.tsx
在“检查多个 API 密钥”界面中：
- 增加单密钥验证功能
- 实现删除单个API密钥的功能
- 为每个密钥添加删除和验证按钮以优化界面
- 在验证期间禁用其他操作以避免冲突
- 为密钥删除功能添加样式化图标
Description:
- Add single key checking functionality
- Implement ability to remove individual API keys
- Improve UI with remove and check buttons for each key
- Disable actions during checking to prevent conflicts
- Add styled remove icon for key deletion
1. 现在的界面，可以只检查指定的密钥，并提供移除操作：
2. 检查密钥过程中会禁用一些相关操作
3. 检查结果
4. 可以移除某个key
> feat: Enhance API Key Management in Provider Settings

- src/renderer/src/pages/translate/TranslatePage.tsx
- src/renderer/src/services/ApiService.ts
> fix: translate error handle

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/translate/TranslatePage.tsx
> feat: synced scrolling for translation page

- src/renderer/src/utils/index.ts
> fix: Refine special character removal in utility function

- package.json
- src/main/ipc.ts
- src/main/services/GeminiService.ts
- src/main/services/KnowledgeService.ts
- src/main/services/ProxyManager.ts
- src/main/services/WebDav.ts
- yarn.lock
- Add ProxyManager service to handle system, custom, and no proxy configurations
- Integrate proxy support for Gemini, Knowledge, and WebDav services
- Add fetch-socks and undici for advanced proxy handling
- Enhance proxy configuration with environment variable and session management
#2616 重新PR
> feat(Proxy): Implement proxy management system

- src/renderer/src/store/messages.ts
> fix:message_status

- src/renderer/src/utils/error.ts
> fix:abortError handle

- src/main/services/ProxyManager.ts
> fix(Proxy): improve system proxy monitor logic and proxyManager init

- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
> fix(TopicsTab): Ensure active topic is updated correctly on deletion

- src/renderer/src/pages/agents/components/AddAgentPopup.tsx
- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
预览效果图如下，解决 #3203 ，猫大看看有没有添加的必要 😂
> feat: 提示词输入框添加Token预估数

- src/renderer/src/webSearchProvider/ExaProvider.ts
> fix(websearch): exa return empty content

- src/renderer/src/config/prompts.ts
fix https://github.com/CherryHQ/cherry-studio/issues/3089
> feat(prompts): Translate prompts to English and enhance clarity

- src/renderer/src/config/models.ts
- src/renderer/src/providers/OpenAIProvider.ts
- Added Gemma3 as a vision model.
- Improved functioncall model check logic.
- Introduced a new method to clean tool call arguments, ensuring proper formatting and extraction of parameters.
- Adjusted tool call handling in OpenAIProvider to accommodate new GLM-4-alltools model checks and argument processing.
效果图
> feat(MCP): Support GLM-4-alltools

- src/renderer/src/pages/settings/WebSearchSettings/WebSearchProviderSetting.tsx
1. add check button for apihost websearch
2. fix this
> fix(websearch): add check button and format apihost

- .github/workflows/nightly-build.yml
- .github/workflows/pr-ci.yml
为仓库添加nightly build和pr build test工作流，可以在每晚看到main分支的build情况，同时实现pr合并前的构建测试
> refactor(actions): Add nightly and pr-ci workflows

- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
Fix API URL length causing display style issues
> fix api url display

- .github/workflows/nightly-build.yml
- 改进nightly build打包内容命名格式
- 改进summary流程
- 添加Checksum
> chore(workflows): nightly build refactor

- src/renderer/src/providers/OpenAIProvider.ts
fix: https://github.com/CherryHQ/cherry-studio/issues/3471
> refactor: handle tool content differently for doubao and deepseek 

- src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
> fix: MCP switch button display bug  (#3481)

- src/renderer/src/hooks/useMermaid.ts
- src/renderer/src/pages/home/Markdown/Mermaid.tsx
> fix(mermaid): Mermaid theme not change after theme toggling

- src/renderer/src/pages/home/Markdown/CitationTooltip.tsx
- src/renderer/src/pages/home/Markdown/Link.tsx
- src/renderer/src/pages/home/Markdown/Markdown.tsx
- src/renderer/src/pages/home/Messages/MessageContent.tsx
> feat: add support for citation preview

- CONTRIBUTING.md
- README.md
- docs/README.ja.md
- docs/README.zh.md
- src/renderer/src/pages/settings/AboutSettings.tsx
Fixes https://github.com/CherryHQ/cherry-studio/issues/3477
> fix: update url

- src/renderer/src/pages/home/Markdown/PlantUML.tsx
PlantUML 的 Popup 现在只有下载图片的功能，相较于 Mermaid 缺少了缩放与复制。
> feat(PlantUML): Add zoom and copy function to PlantUML component

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/DataSettings/MarkdownExportSettings.tsx
- src/renderer/src/store/settings.ts
- src/renderer/src/utils/export.ts
- src/renderer/src/utils/index.ts
Resolve https://github.com/CherryHQ/cherry-studio/issues/3499
> feat: enable automatic conversion of math code to $$ during export

- src/renderer/src/pages/home/Messages/MessageAttachments.tsx
- src/renderer/src/services/FileManager.ts
> feat: image attachment copy and download (#3488)

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> refactor: simplify new topic shortcut logic in Inputbar

- src/renderer/src/utils/mcp-tools.ts
1. Improve filterPropertieAttributes to handle nested object and array types, preserving their structure while filtering attributes.
2. Make parameters optional when no properties exist. (Fix #3270)
- https://ai.google.dev/api/caching#FunctionDeclaration
- https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools
- https://json-schema.org/understanding-json-schema/reference/type
1. Add the [Filesystem MCP Server](https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem) to MCP Servers list.
2. Use the `Gemini 2.0 Flash` model and enable the `filesystem` MCP server in the chat.
3. Try telling the model to read some folders and files.
4. Bug 1 is encountered: Nested object's properties not being filtered properly.
```
Invalid JSON payload received. Unknown …
```
> fix(mcp-tools): Enhance object nested properties filtering

- package.json
- src/renderer/src/pages/home/Messages/Messages.tsx
> fix: race condition in new context event

- src/renderer/src/config/providers.ts
> fix: update API URL for together provider

- src/main/services/MCPService.ts
- src/renderer/src/providers/AnthropicProvider.ts
- src/renderer/src/providers/GeminiProvider.ts
- src/renderer/src/providers/OpenAIProvider.ts
- src/renderer/src/services/ApiService.ts
fix https://github.com/CherryHQ/cherry-studio/issues/3475
> feat[MCP]: Optimize list tool performance.

- src/renderer/src/utils/mcp-tools.ts
fix: https://github.com/CherryHQ/cherry-studio/issues/3592
> fix: correct typo in properties variable and add null check

- src/renderer/src/providers/OpenAIProvider.ts
fix: https://github.com/CherryHQ/cherry-studio/issues/3627
https://github.com/CherryHQ/cherry-studio/issues/3546
> fix[MCP]: enhance tool call handling in OpenAIProvider

- src/main/reranker/BaseReranker.ts
- src/main/reranker/SiliconFlowReranker.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/services/KnowledgeService.ts
- src/renderer/src/types/index.ts
区分了嵌入的baseurl,apikey和重排的baseurl,apikey
需要先合并上一个PR
> fix(reranker): fix reranking API integration with own parameters

- src/renderer/src/pages/settings/MCPSettings/NpxSearch.tsx
fix:https://github.com/CherryHQ/cherry-studio/issues/3633
> refactor(NpxSearch): improve type safety and error handling

- src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
- src/renderer/src/pages/settings/ProviderSettings/ModelListSearchBar.tsx
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
> feat: add a search bar to model list

- src/main/reranker/JinaReranker.ts
- src/main/reranker/SiliconFlowReranker.ts
- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/pages/knowledge/components/AddKnowledgePopup.tsx
- src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
> fix(knowledge): show more info

- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
fix: #3761
在API密钥输入字段中撤销操作时出现闪烁问题，这是由于React的受控组件模式与浏览器的原生撤销功能之间的冲突所致
1. 当按下Ctrl+Z时，浏览器试图恢复之前的输入值
2. 然后React立即通过`formatApiKeys`重新格式化它
3. 这导致了状态更新的快速循环，从而引起闪烁
> fix: apikey input flickering

- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/pages/apps/App.tsx
> feat: 支持直接在小程序界面右键隐藏小程序

- src/main/services/ShortcutService.ts
fix:  some shortcuts not work, like #3863
> fix [!important]: some shortcuts not work

- packages/shared/config/constant.ts
远期可以进一步考虑直接自动使用 https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml 加上自定义扩展集的方式，减轻维护负担
Should consider directly and automatically using https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml along with a custom extension set to reduce the maintenance burden.
> feat: Update text-based file extensions for EDAs

- src/renderer/src/assets/styles/markdown.scss
- yarn.lock
Katex和MathJax块横向自动滚动
fix #3639
> feat: Katex and MathJax blocks horizontally auto-scroll

- src/renderer/src/hooks/useAppInit.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/pages/settings/AboutSettings.tsx
- src/renderer/src/store/settings.ts
将手动检查更新的设置更改为自动检查更新，更新相关的状态管理和界面文本，以提升用户体验。
> feat: 提高自动检查更新功能设置易读性

- README.md
Add PaperMaterial Theme( https://github.com/rainoffallingstar/CherryStudio-PaperMaterial) in README.
> Add PaperMaterial Theme in README

- src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
modified:   src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
> feat: exclude rerank models from mention dropdown

- src/renderer/src/hooks/useMessageOperations.ts
> feat(message): calculate token usage when message content is updated

- src/main/reranker/BaseReranker.ts
- src/main/reranker/JinaReranker.ts
- src/main/reranker/SiliconFlowReranker.ts
- src/main/reranker/VoyageReranker.ts
- src/main/services/KnowledgeService.ts
> fix(Reranker): 修复rerank 400 and 完善错误信息

- src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
- src/renderer/src/pages/settings/MCPSettings/NpxSearch.tsx
> refactor: mcp setting ui refactor

- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
> fix(TopicsTab): Topic prompts cannot be cleared

- src/renderer/src/pages/home/Chat.tsx
- src/renderer/src/pages/home/Messages/ChatNavigation.tsx
- src/renderer/src/pages/home/Messages/MessageAnchorLine.tsx
- src/renderer/src/pages/home/Messages/MessageGroup.tsx
- src/renderer/src/pages/home/Messages/MessageGroupMenuBar.tsx
- src/renderer/src/pages/home/Messages/MessageGroupModelList.tsx
- src/renderer/src/store/messages.ts
1、修复foldSelected问题；
2、优化导航按钮布局，不依赖topicPosition；
> fix: fix fold selected

- src/renderer/src/services/ApiService.ts
- src/renderer/src/services/MessagesService.ts
> fix(ApiService): context clear failed

- src/renderer/src/pages/settings/ProviderSettings/ApiCheckPopup.tsx
This PR optimizes the API key validation process by implementing parallel checks using Promise.all. Testing shows this approach reduces validation time by approximately 80%, significantly improving user experience when validating multiple API keys simultaneously.
> Optimize API key validation by implementing parallel checks

- src/renderer/src/hooks/useTopic.ts
> fix: race condition in topic auto renaming

- src/main/services/MCPService.ts
> fix(MCPService): prefix tool IDs with 'f' for consistency

- src/renderer/src/components/Popups/AddAssistantPopup.tsx
- Added keyboard arrow navigation for assistant selection
- Implemented visual highlighting of selected items
- Added Enter key support to confirm selection
- Ensured selected items automatically scroll into view
Fixes #4012
> Add keyboard navigation and selection highlighting for AddAssistantPopup

- src/renderer/src/config/models.ts
> fix(models): reorganize gemini websearch model lists

- src/renderer/src/pages/home/Markdown/Artifacts.tsx
- src/renderer/src/pages/home/Markdown/CodeBlock.tsx
- src/renderer/src/pages/home/Markdown/Markdown.tsx
- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageGroup.tsx
- src/renderer/src/pages/home/Messages/Messages.tsx
* Updated CodeBlock component to include a StickyWrapper for better positioning of action buttons.
* Adjusted styles for Message components to allow for visible overflow, enhancing content display.
* Added a preformatted block rendering in Markdown to improve code presentation.
issue: #3957
实现方式：
固定的高度的容器（overflow: auto）中有滚动的消息流。
保证容器内嵌套的所有元素非overflow: hidden、auto 或 scroll
CodeBlock中设定一个sticky元素，sticky效果就可以绑定到滚动上下文
暂不清楚是否会影响其他布局下的效果
> optimize: Sticky CopyButton in CodeBlock

- src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
> perf: improve modellist search bar responsiveness (and memorization)

- src/renderer/src/assets/styles/ant.scss
> fix(UI): enhance scrollbar visibility and dropdown menu overflow handling

- src/renderer/src/pages/home/Messages/ChatFlowHistory.tsx
fix: chat history dark theme, sync with app theme
resolve #4252
> fix: chat history dark theme

- src/renderer/src/pages/settings/ProviderSettings/ModelEditContent.tsx
> feat:One-click copy model id

- src/renderer/src/pages/knowledge/components/KnowledgeSearchPopup.tsx
> fix: enable text selection in knowledge base search results

- src/main/services/NutstoreService.ts
- src/renderer/src/pages/settings/DataSettings/NutstoreSettings.tsx
> fix(NutstoreService): Fix slash handling in path processing #4208

- src/renderer/src/utils/mcp-tools.ts
> fix(mcp-tools): enhance tool lookup to match by name in addition to ID

- src/renderer/src/pages/home/Messages/MessageGroup.tsx
修复错误设置消息框overflow: visible。导致横向布局时，多模型回答时消息溢出；横向滚动条消失
已根据不同布局判断溢出行为控制，并添加注释。
pr: #4205
> fix(CodeBlock): incorrect behavior of message in multiple models

- src/renderer/src/services/NutstoreService.ts
> fix(nutstore): restore from nutstore #4318

- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
> feat(Anthropic): Enable Anthropic 128k context beta feature

- src/renderer/src/pages/home/Tabs/TopicsTab.tsx
> fix(TopicsTab): Topic prompt word modification does not take effect immediately

- src/renderer/src/services/BackupService.ts
fix: webdav backup resume and modal problem
- auto backup will retry, avoiding immediately failure after system resume by giving time to reconnect to network
- only one modal error message will show, auto backup continues after modal dismissed
resolve #4187
> fix: webdav backup resume and modal problem

- src/renderer/src/pages/home/Messages/ChatNavigation.tsx
缩小Navigation Button触发区域，避免与对话按钮冲突
- fix #4363 
- fix #4266 
- fix #4035
- fix #3995
> fix(ChatNavigation): improve navigation button collapse functionality

- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
- src/renderer/src/pages/settings/AssistantSettings/index.tsx
feat: render markdown when show assistant prompt
- render markdown
- click to edit, blur to render
solve #4360
> feat: render markdown when show assistant prompt

- src/renderer/src/components/QuickPanel/view.tsx
- src/renderer/src/pages/home/Inputbar/AttachmentButton.tsx
- src/renderer/src/pages/home/Inputbar/AttachmentPreview.tsx
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
1：优化输入框附件显示；
2：优化快捷面板提示条溢出问题；
3：优化outsideclick文件；
> feat(QuickPanel): Optimize QuickPanel

- src/renderer/src/pages/home/Messages/MessageAnchorLine.tsx
> feat: Support bottom anchor in message anchor line

- src/renderer/src/pages/home/Markdown/CodeBlock.tsx
> fix: wrap inline code

- src/renderer/src/pages/home/Messages/MessageContent.tsx
- src/renderer/src/types/index.ts
- src/renderer/src/utils/formats.ts
> fix(MessageContent): handle optional chaining for grounding metadata and citations

- src/main/services/MCPService.ts
fix: #4239 
https://github.com/CherryHQ/cherry-studio/issues/3264#issuecomment-2774480133
> fix(McpService): improve client connection handling with error logging

- src/renderer/src/config/models.ts
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/services/ApiService.ts
- src/renderer/src/store/websearch.ts
> fix(websearch): improve web search enablement logic

- src/renderer/src/pages/home/Messages/MessageImage.tsx
- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
修复了两个问题：
1. fix #4399 
2. 点击编辑回复内容的时候，如果有图片，内容中没有图片markdown内容的问题
> fix: 解决聊天页面图片复制失败的问题和点击编辑回复的时候，不显示图片url的问题

- src/main/services/WindowService.ts
fix:[mac] lower window level not to cover pinyin input method
> fix: [mac] lower window level not to cover pinyin input method

- src/renderer/src/components/Popups/UserPopup.tsx
- src/renderer/src/pages/settings/ProviderSettings/AddProviderPopup.tsx
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- src/renderer/src/services/ImageStorage.ts
一个小功能：在自定义模型提供商处添加模型logo上传
@kangfenmao
> feat: add model provider logo upload

- src/main/services/WindowService.ts
fix: [mac] issues related to fullscreen mode, and cleanup some useless codes
solve #4602 
may solve #4368
> fix: [mac] issues related to fullscreen mode

- src/renderer/src/config/models.ts
> fix: O3 config text-embedding-3-small duplicate

- src/main/index.ts
- src/main/services/MCPService.ts
> Clean up MCPService connections on app quit

- src/renderer/src/pages/home/Markdown/CodeBlock.tsx
- src/renderer/src/pages/home/Tabs/SettingsTab.tsx
- Resolve #4663 
Before：
After：
> feat(CodeBlock): add tooltips for collapse and copy buttons

- package.json
- src/main/mcpServers/memory.ts
- yarn.lock
优化了memory.json文件的加载过程，只加载一次，其它涉及图谱的操作均在内存中完成，提高效率；
注意新引入了async-mutex软件包，需要yarn install安装。
> 重构了memory.ts，增加了文件写入锁，解决了并行写入导致记忆文件错误的问题；

- packages/shared/IpcChannel.ts
- src/main/ipc.ts
- src/main/services/MCPService.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
- src/renderer/src/pages/settings/MCPSettings/McpPrompt.tsx
- src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
- src/renderer/src/pages/settings/MCPSettings/McpTool.tsx
- src/renderer/src/pages/settings/MCPSettings/NpxSearch.tsx
- src/renderer/src/types/index.ts
https://modelcontextprotocol.io/docs/concepts/prompts
https://github.com/user-attachments/assets/66107752-19f2-43b7-9c46-89ed4f313801
https://github.com/user-attachments/assets/b410ab1c-cbc5-4105-bc97-baa45a4efa0a
> Feat/mcp support MCP prompt

- src/renderer/src/pages/settings/MCPSettings/NpxSearch.tsx
- src/renderer/src/pages/settings/MCPSettings/index.tsx
- src/renderer/src/pages/settings/index.tsx
https://github.com/user-attachments/assets/0d40f788-5d02-4cc8-bf2b-db946989cc5b
> Feat/improve UI mcp settings

- src/renderer/src/pages/home/Tabs/AssistantItem.tsx
> feat(AssistantItem UI): 优化助手Emoji显示

- src/renderer/src/config/models.ts
- src/renderer/src/config/providers.ts
- src/renderer/src/pages/settings/ProviderSettings/EditModelsPopup.tsx
- 更新百炼新APIKey和模型页面链接
- 优化百炼平台模型分类
- 优化搜索模型匹配优先级，提高手动设置的优先级
- 解决 #4655  #4431
> fix: Update dashscoop provider configuration and enhance model editing functionality

- src/renderer/src/config/prompts.ts
- src/renderer/src/providers/WebSearchProvider/LocalSearchProvider.ts
- src/renderer/src/services/ApiService.ts
- src/renderer/src/services/WebSearchService.ts
- src/renderer/src/utils/fetch.ts
Add support for webpage summarization, direct URL references, and better query processing using a structured XML format. Move web content fetching to dedicated utility functions with improved error handling and format options.
https://github.com/user-attachments/assets/522cd440-6858-40c1-b168-f7ac33e79e2d
> Enhance web search with XML-based query extraction

- src/main/services/MCPService.ts
在 Electron 应用中，`process.env.PATH` 无法正确获取系统的 PATH 环境变量，这导致一些依赖系统命令的功能无法正常工作。
1. 新增 `getSystemPath` 方法，通过执行 shell 命令来获取真实的系统 PATH
2. 支持多种 shell 环境（zsh、bash、fish）
3. 优化 `getEnhancedPath` 方法，合并系统 PATH 和应用 PATH
4. 使用 `memoize` 缓存系统 PATH 获取结果，提高性能
- 根据用户使用的 shell 类型（zsh/bash/fish）执行相应的命令获取 PATH
- 在 Windows 系统上使用 PowerShell 获取 PATH
- 自动检测并加载 shell 配置文件（如 .zshrc, .bashrc 等）
- 优雅处理错误情况，当获取系统 PATH 失败时回退到原始 PATH
- https://github.com/CherryHQ/cherry-studio/issues/4689
> fix(MCPService): 增加获取系统 PATH 的功能, 修复 process.env.PATH 无法获取系统PATH的问题

- src/renderer/src/components/Popups/AddAssistantPopup.tsx
- src/renderer/src/components/QuickPanel/view.tsx
- src/renderer/src/windows/mini/home/HomeWindow.tsx
fix [issue ](https://github.com/CherryHQ/cherry-studio/issues/4763#issuecomment-2799976659)related:
> fix: numpad enter not work

- src/main/services/WindowService.ts
> fix: [mac] fullscreen changed when switch by clicking dock icon

- src/renderer/src/windows/mini/home/HomeWindow.tsx
> fix: quickAssistant transalte not work by key select

- src/renderer/src/config/models.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
> feat(Grok): add isGrokModel function and update systemMessage handling for Grok models

- src/renderer/src/config/models.ts
> feat(models): add gpt-4.1 model to visionAllowedModels

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
> fix(OpenAIProvider): remove unnecessary o-series model stream restriction

- README.md
- docs/README.ja.md
- docs/README.zh.md
推荐一下我自己写的Maple Neon主题，能够自动切换黑夜/日间主题，输入框采用动态霓虹效果，为Markdown输出内容等都进行了样式适配。
> 为各语言的README都添加了Maple-Neon主题.

- README.md
- docs/README.ja.md
- docs/README.zh.md
不好意思，之前一个PR的主题链接重定向到了错误的仓库，我修正了这一错误，一并修改了中文和日文主题的主题排版。:D
> fix(ReadMe): the redirection error of the Maple Neon theme

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
> fix(OpenAIProvider): Filter empty system prompts

- src/renderer/src/pages/agents/components/AddAgentPopup.tsx
> fix(AddAgentPopup): update form handling and simplify prompt input layout

- src/renderer/src/pages/home/Messages/MessageContent.tsx
> fix: knowledge citations

- src/renderer/src/init.ts
> fix: Nutstore auto-sync when app starts

- src/renderer/src/config/models.ts
https://ai.google.dev/gemini-api/docs/thinking
> feat(models): update gemini model identification logic to be more general

- packages/shared/IpcChannel.ts
- src/main/ipc.ts
- src/main/services/AppUpdater.ts
- src/main/services/ConfigManager.ts
- src/preload/index.d.ts
- src/preload/index.ts
- src/renderer/src/hooks/useSettings.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/AboutSettings.tsx
fix: should not download when autoupdate is false
- fix the logic of download&autoInstallOnAppQuit
solve: #5008
> fix: should not download when autoupdate is false

- src/renderer/src/pages/home/Inputbar/AttachmentPreview.tsx
- src/renderer/src/pages/home/Messages/MessageAttachments.tsx
- src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
- fix #4971 
Before：
https://github.com/user-attachments/assets/f17c17ee-23e1-48ca-bc4d-da645f48352b
https://github.com/user-attachments/assets/20c316f1-f756-4f12-8b1f-00556cd71466
After：
https://github.com/user-attachments/assets/ac6a124d-c5da-44fb-b502-a973c60e81c4
https://github.com/user-attachments/assets/c1d1493b-70a6-44ab-87c5-e28eea0ca381
> fix (UI): Resolve the issue of overly long file names and path names not being displayed correctly

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/pages/settings/DataSettings/WebDavSettings.tsx
- src/renderer/src/services/BackupService.ts
- src/renderer/src/store/settings.ts
fix #4276 #3878
- Add maximum backups feature to WebDAV settings
> feat: implement maximum backups feature in WebDAV settings

- src/renderer/src/utils/index.ts
优化mcp搜索配置提取逻辑，兼容readme中有多个mcp配置的场景
> feat: mcp configuration extraction logic optimization

- src/renderer/src/pages/settings/ProviderSettings/ModelList.tsx
- fix #4954
Before：
https://github.com/user-attachments/assets/c9d8a4ae-9c05-4cf2-a21f-6a543f0c0b1b
After：
https://github.com/user-attachments/assets/d8c26bc2-d0b8-4b1e-9bba-9a8bbeeb9996
> refactor(ModelList): extract NameSpan component and adjust styling for better layout

- src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
代码里面 header 字符串分割是按照 : 进行，但是placeholder是按照 = ，误导了用户 #5001
> fix(MCPService):修复MCP server 请求头不生效

- electron-builder.yml
> fix: language error

- src/main/ipc.ts
- src/renderer/src/pages/settings/AboutSettings.tsx
- src/renderer/src/types/index.ts
fix https://github.com/CherryHQ/cherry-studio/issues/4944
> feat: disable auto update in portable exe

- src/renderer/src/config/minapps.ts
This reverts commit aed9c04c200be08fdb289e63a094279f5d8df327.
> Revert "fix(minapps): remove AI Studio entry from default mini apps list"

- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/pages/knowledge/KnowledgePage.tsx
> fix(knowledge): change search ui and fix search bug

- src/renderer/src/config/prompts.ts
- src/renderer/src/pages/home/Messages/MessageContent.tsx
- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
- src/renderer/src/pages/knowledge/KnowledgePage.tsx
- src/renderer/src/services/ApiService.ts
> fix(knowledge): fix citation bug and optimize extract logic

- src/renderer/src/init.ts
> fix: should give more time to init autosync

- src/renderer/src/assets/styles/animation.scss
- src/renderer/src/components/Popups/NutsorePathPopup.tsx
- src/renderer/src/components/Popups/SearchPopup.tsx
- src/renderer/src/components/Popups/SelectModelPopup.tsx
- src/renderer/src/components/Popups/TemplatePopup.tsx
- src/renderer/src/components/Popups/TextEditPopup.tsx
- src/renderer/src/components/Popups/UserPopup.tsx
- src/renderer/src/pages/knowledge/components/KnowledgeSearchPopup.tsx
- src/renderer/src/pages/settings/AssistantSettings/index.tsx
- src/renderer/src/pages/settings/MCPSettings/EditMcpJsonPopup.tsx
- src/renderer/src/pages/settings/ModelSettings/TopicNamingModalPopup.tsx
- src/renderer/src/pages/settings/ProviderSettings/ProviderSettingsPopup.tsx
- src/renderer/src/pages/settings/ProviderSettings/SelectProviderModelPopup.tsx
- https://github.com/CherryHQ/cherry-studio/pull/4901
- https://github.com/CherryHQ/cherry-studio/issues/4817
> style: fix animation

- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
When the model provider is toggled (OFF to ON), it is moved to the top of the provider setting for convenience. The change is minimal. It doesn't conflict with current dragging functionality, users can still drag to adjust positions according to their favors.
> feat(ProviderSettings): move model provider to the top when toggled

- src/renderer/src/pages/settings/WebSearchSettings/BasicSettings.tsx
- src/renderer/src/store/websearch.ts
> fix(settings): handle undefined content limit in BasicSettings component

- .github/workflows/nightly-build.yml
These lines were deleted in `release.yml` in commit 75f98608.
> fix(ci): Remove a step in the nightly build pipeline

- src/main/index.ts
- src/main/utils/file.ts
Just like VSCode, this PR makes all appdata store in the same dir of executable file, then the whole app is portable, including configurations.
> feat: support portable config dir

- src/renderer/src/pages/home/Messages/MessageContent.tsx
After this PR:
Fixes #
`message?.metadata?.annotations?.map` 这里的optional chain不能保证安全，如果annotation是object的话（copilot的response里是object）就会报下面截图中的错误。
```
{
"choices": [
{
"finish_reason": "stop",
"index": 0,
"delta": {
"content": null,
"annotations": {
"CodeVulnerability": [
{
"id": 0,
"start_offset": 48,
"end_offset": 48,
"details": { "type": "general" },
"citations": {},
},
],
},
"copilot_annotations": {
"CodeVulnerability": [
{
"id": 0,
"start_offset": 48,
"end_offset": 48,
"details": { "type": "general" },
"citations": {},
},
],
},
},
},
],
"created": 0000,
"id": "",
"usage": {
"completion_tokens": 305,
"prompt_tokens": 10,
"total_tokens": 315,
},
"model": "gpt-4.1-2025-04-14",
"system_fingerprint": "fp_11111",
}
```
no breaking changes
This checklist is not enforcing, but …
> fix: Resolve unsafe map call in MessageContent.tsx

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/pages/home/Messages/MessageContent.tsx
- src/renderer/src/providers/AiProvider/BaseProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/services/ApiService.ts
After this PR:
fix: image abort error and message render error
Fixes #
```release-note
NONE
```
> fix: image abort error and message render error

- src/renderer/src/providers/WebSearchProvider/SearxngProvider.ts
- 将大模型的参考来源从searxng搜索结果摘要改为实际URL内容
1. 搜索结果摘要存在信息碎片化问题
2. 实际页面内容包含更完整的上下文信息
3. 提升大模型回答的事实准确性
> 获取searxng搜索结果url的内容作为大模型回答的参考，而不是使用searxng搜索结果的摘要内容

- src/renderer/src/config/models.ts
Before this PR:  Some websearch models are missing.
After this PR:   fix it
Fixes #5344 
```release-note
NONE
```
> feat(models): add new  search models 

- packages/shared/IpcChannel.ts
- src/main/services/ProtocolClient.ts
- src/main/services/urlschema/mcp-install.ts
- src/renderer/src/env.d.ts
- src/renderer/src/hooks/useMCPServers.ts
- src/renderer/src/services/NavigationService.ts
Test URL: [cherrystudio://mcp/install?servers=ewogICJtY3BTZXJ2ZXJzIjogewogICAgImV2ZXJ5dGhpbmciOiB7CiAgICAgICJjb21tYW5kIjogIm5weCIsCiAgICAgICJhcmdzIjogWwogICAgICAgICIteSIsCiAgICAgICAgIkBtb2RlbGNvbnRleHRwcm90b2NvbC9zZXJ2ZXItZXZlcnl0aGluZyIKICAgICAgXQogICAgfQogIH0KfQ](cherrystudio://mcp/install?servers=ewogICJtY3BTZXJ2ZXJzIjogewogICAgImV2ZXJ5dGhpbmciOiB7CiAgICAgICJjb21tYW5kIjogIm5weCIsCiAgICAgICJhcmdzIjogWwogICAgICAgICIteSIsCiAgICAgICAgIkBtb2RlbGNvbnRleHRwcm90b2NvbC9zZXJ2ZXItZXZlcnl0aGluZyIKICAgICAgXQogICAgfQogIH0KfQ)
https://github.com/user-attachments/assets/e7b31a08-3940-4827-82c0-c5c8c8f8e81c
Implement handler for cherrystudio://mcp/install URLs to add MCP servers from encoded configuration data. Supports multiple server configuration formats and adds a new IPC channel for server …
> Add MCP server installation via URL protocol

- electron-builder.yml
- src/main/index.ts
- src/main/services/ProtocolClient.ts
Implements setup for deep linking (URI scheme handling) when the application is run as an AppImage on Linux. It creates or updates a `.desktop` file in the user's local applications directory (`~/.local/share/applications/`) to register the `cherrystudio://` URI scheme with the AppImage executable.
Users running the application via AppImage on Linux not have deep linking functionality enabled, requiring manual steps to associate the `cherrystudio://` scheme with the AppImage path.
After this PR:
When the application runs as an AppImage, it attempts to configure the desktop environment to handle `cherrystudio://` links by creating/updating `~/.local/share/applications/cherrystudio.desktop`.
Fixes #5336
The following alternatives were …
> feat: Implement deep linking for AppImage on Linux

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> feat: Enable image generation in assistant based on model selection

- src/renderer/src/pages/home/Messages/MessageTools.tsx
- src/renderer/src/utils/shiki.ts
> feat: tooluse result display style optimization

- .github/workflows/nightly-build.yml
- .github/workflows/pr-ci.yml
- .github/workflows/release.yml
After this PR:
Fixes #
```release-note
```
> chore(workflows): update workflows for new repo structure

- src/renderer/src/services/ModelMessageService.ts
有些模型不會自動判斷關鍵字，導致誤判
After this PR:
加入空格，讓模型清楚斷句，不會有誤判
Fixes #
```release-note
```
> fix: fix the formating error on qwen3

- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
- src/renderer/src/providers/AiProvider/GeminiProvider.ts
- src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Before this PR: 在检查模型是否可用时没有限制token用量
After this PR: 
- 限制检查模型时的最大输出token数
- 对于可以限制思维链长度的推理模型也限制了思维链长度
- 对于可以关闭推理功能的模型（qwen3）显式关闭了推理功能。
之前的版本在进行模型可用性测试时没有限制输出token数。虽然不会造成多少浪费，但是能省一点是一点。
另外，限制思维链长度和关闭推理模式也能有效降低测试推理模型可用性时的耗时。
```release-note
NONE
```
> feat: minimize token usage when testing model

- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
- src/renderer/src/providers/AiProvider/GeminiProvider.ts
- src/renderer/src/providers/AiProvider/OpenAICompatibleProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
After this PR:
Fixes #
```release-note
```
> fix: move start_time_millsec initialization

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/apps/App.tsx
> fix: ensure correct handling of custom mini app updates and removals

- src/main/ipc.ts
当系统的theme变化后，title bar没有自动变化
After this PR:
当系统的theme变化后，title bar也会自动变化
https://github.com/user-attachments/assets/d62e26be-b14c-4f77-9309-9e634769d5cf
Fixes https://github.com/CherryHQ/cherry-studio/issues/4616#issuecomment-2871733259
```release-note
```
> fix(ipc): enhance theme handling with title bar overlay updates and broadcast notifications

- src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
- src/renderer/src/store/thunk/messageThunk.ts
After this PR:
Fixes #5904 
```release-note
```
> fix: timer stop

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
- src/renderer/src/store/migrate.ts
知识库提问的时候问题重写功能调用了错误的模型，导致知识库提问重写失败
助手设置->知识库意图识别选项默认值丢失
After this PR:
知识库提问的时候问题可以调用正确的模型进行重写
知识库意图识别数据默认设置为 off
> fix: OpenAIResponseProvider summaryForSearch impl model wrong

- docs/branching-strategy.md
After this PR:
- Remind contributors that for PRs related to UI components, pictures need to be attached to help reviewer quickly understand the changes.
Fixes #
```release-note
```
> docs: Add Photo instructions to the branch strategy document

- src/renderer/src/pages/home/Messages/MessageTokens.tsx
Token consumption information is mixed together, which is not conducive to display optimization.
After this PR:
Optimize the labeling of the three token consumption modes by separating them with `span` tags.
Fixes #
```release-note
```
> feat: Optimize the display method for the three modes

- src/main/services/WebviewService.ts
remove chrome version assignment. Inconsistencies in versions and behavior may exacerbate login issues
> fix(WebviewService): remove chrome version assignment

- src/renderer/src/store/messageBlock.ts
After this PR:
Fixes #
```release-note
```
> fix: improve citation deduplication logic for non-knowledge citations

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
不能使用话题提示词
After this PR:
Fixes #5968
```release-note
```
> fix: append topic prompt if exists

- src/renderer/src/assets/styles/index.scss
> fix: define line-clamp for compatibility

- src/renderer/src/config/models.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
- src/renderer/src/store/thunk/messageThunk.ts
1. 生成图片时可能有文字，可能没文字，没文字会导致有个空的消息块
2. 通过providers映射减少冗余代码
After this PR:
fix it
Fixes #
```release-note
```
> fix: enhance image block handling in message processing

- README.md
更新贡献者数据源。
After this PR:
Fixes #
```release-note
```
> docs: 贡献者数据源

- src/renderer/src/config/models.ts
- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
- src/renderer/src/providers/AiProvider/BaseProvider.ts
- src/renderer/src/providers/AiProvider/GeminiProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
根据模型名称判断是否支持温度
温度判断不准确
After this PR:
温度判断准确
Fixes #5733 #5454
```release-note
```
> fix: inaccurate temperature param

- src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
初始化一个新的MCP Server且此MCP服务异常时，没有防止用户多次点击启用开关，从而导致出现多个重复的异常确认弹框
复现方式：
After this PR:
优化项：设置loading状态防止用户频繁点击开关
```release-note
```
> fix: Update Server McpSettings

- src/renderer/src/providers/AiProvider/GeminiProvider.ts
After this PR:
Fixes #
```release-note
```
> fix: update geminiapi check

- src/renderer/src/utils/mcp-tools.ts
fix https://github.com/CherryHQ/cherry-studio/issues/6050
> fix: mcp params error(issues/6050)

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/store/thunk/messageThunk.ts
After this PR:
Fixes #6059 
```release-note
```
> fix: Update the state of the last message block as a fallback

- src/renderer/src/pages/settings/ProviderSettings/SelectProviderModelPopup.tsx
许多模型名称很长，目前模态框太短，无法完全显示
After this PR:
仅仅是一点样式调整，width从300变成400，不会带来破坏式影响
NONE
```release-note
NONE
```
> 拓宽”请选择要检测的模型“模态框

- src/renderer/src/components/ContextMenu/index.tsx
- src/renderer/src/pages/home/Messages/CitationsList.tsx
- src/renderer/src/pages/home/Messages/Message.tsx
> feat: add citation list right-click copy

- src/renderer/src/config/models.ts
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
update CN name of model provide, update models
> Gitee AI:update name, update models

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
1. 不支持的文件拖放或者粘贴，没有任何提示
2. 粘贴文件后光标没有了，就不能再复制
After this PR:
1. 添加更加友好的提示
2. 修复光标没有了不能复制的问题
https://github.com/user-attachments/assets/7adc1b53-93c6-43b4-9d13-81e07d0b16f9
3. 添加一个蒙层
Fixes #
```release-note
feat: Drop file improvements
```
> feat: Drop file improvements

- src/renderer/src/config/minapps.ts
After this PR:
Fixes #
```release-note
- Change the minimax to new URL
```
> fix: change minimax's URL

- src/renderer/src/pages/apps/AppsPage.tsx
After this PR:
Fixes #
```release-note
- Ensure last app is displayed when no filtered apps are found
```
> fix: Ensure last app is displayed when no filtered apps are found

- src/renderer/src/windows/mini/home/HomeWindow.tsx
#6101 
After this PR:
Fixes #
#6101 
```release-note
```
> fix: Prevent sending message during input method composition in mini window

- src/renderer/src/store/thunk/messageThunk.ts
> fix: group message resend

- src/renderer/src/pages/home/Messages/MessageGroupModelList.tsx
清理代码
After this PR:
- 清理注释
- 清理无用的样式
- 恢复 Segmented 切换动画
- 调整紧凑模式 avatar 大小（28 -> 22）
- 提取 renderLabel
Fixes #
```release-note
```
> refactor: clean up code for `MessageGroupModelList`

- src/renderer/src/i18n/locales/zh-cn.json
After this PR:
Fixes #
```release-note
```
> fix(i18n): websearch has no translation

- src/renderer/src/pages/home/Inputbar/TokenCount.tsx
After this PR:
Fixes #
```release-note
fix: remove infinite token display for max count and simplify context count rendering.
```
> fix: remove infinite token display for max count and simplify context count rendering.

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
修复Github Models中OpenAI系列模型的健康检测错误
> hotfix: github models check error

- src/main/index.ts
- src/main/ipc.ts
- src/main/services/MCPService.ts
- src/main/services/WindowService.ts
- src/main/services/mcp/shell-env.ts
- src/renderer/src/hooks/useMCPServers.ts
- src/renderer/src/pages/home/Inputbar/MCPToolsButton.tsx
延迟 MCP 服务器初始化，加快客户端启动速度
1. McpService 不再使用 new McpService() 默认导出，延迟创建时间
2. IPC 调用的时候开始初始化 mcpService
3. 当 initClinet 函数被前端多次同时调用的时候，会出现多个 client 同时创建的情况（由于第一个还没有创建好，这个时候开始创建第二个，就会出现多个创建过程）加入了 pendingClients promise map，当第一个创建过程开始之后，后续创建直接返回之前的 Promise
4. 移除了部分 log error 对象，由于 error 对象调用堆栈没有特别大的参考意义，仅保留 error.message log
5. 延迟 MCPToolsButton 初始化调用 mcp server, 减少客户端载入时候的卡顿情况
```release-note
```
> refactor: streamline MCP service handling and improve IPC registration

- src/main/services/MCPService.ts
- src/main/utils/mcp.ts
No more random name!
fix: #6077 #5425 #5421 #5265 
After this PR:
Fixes #
```release-note
```
> feat: add buildFunctionCallToolName utility for generating tool names

- src/renderer/src/pages/home/Messages/MessageGroup.tsx
After this PR:
Fixes #
```release-note
```
> fix: 多发消息时除fold布局以外的其他布局不能被渲染

- src/renderer/src/config/models.ts
- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
优化claude token的计算
Fixes #6155 
```release-note
```
> fix: update token limits for Claude models

- src/renderer/src/pages/settings/ProviderSettings/AddModelPopup.tsx
添加模型弹窗中，保存时总是会格式化 group name
After this PR:
有 group name 时直接用
Fixes #6162 
```release-note
```
> hotfix: respect user-defined model group name

- src/renderer/src/pages/knowledge/KnowledgeContent.tsx
修复了Electron新API下不能上传文件的问题
Fixes #
```release-note
```
> fix: update file path resolution in new Electron

- src/renderer/src/pages/home/Messages/MessageTools.tsx
> fix(mcp): mcp result preview is missing parameters

- src/renderer/src/providers/AiProvider/AihubmixProvider.ts
After this PR:
Fixes #
```release-note
```
> Fix aihubmix provider model proxy rule

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
修复了非流式输出下思考块不展示的问题
Fixes #6219 #6302 
```release-note
```
> fix: non-streaming reasoning_content

- src/renderer/src/components/ContentSearch.tsx
- src/renderer/src/hooks/useUpdateHandler.ts
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> fix: #6301

- src/renderer/src/config/models.ts
Adds support for reasoning, websearch and vision for calls to new Anthropic Claude Sonnet 4 and Claude Opus 4 models
> Support Claude 4

- src/renderer/src/providers/AiProvider/GeminiProvider.ts
- Removed unnecessary content accumulation and streamlined chunk processing logic.
- Introduced distinct handling for 'thinking' and 'text' parts, ensuring accurate onChunk calls for both types.
- Enhanced timing tracking for reasoning content, improving overall responsiveness in streaming scenarios.
After this PR:
Fixes #
```release-note
```
> feat: gemini thinking summary support

- src/renderer/src/pages/home/Messages/MessageEditor.tsx
fix https://github.com/CherryHQ/cherry-studio/issues/6327
> fix: editing user messages is not re-sent; it can only be saved#6327

- package.json
- yarn.lock
有些linux启动就crash
After this PR:
启动不会crash
https://releases.electronjs.org/release/v35.4.0
https://github.com/electron/electron/issues/47007
Fixes #6313
```release-note
```
> chore: update electron version to 35.4.0 in package.json and yarn.lock

- src/renderer/src/hooks/useChatContext.ts
- src/renderer/src/pages/home/Messages/Messages.tsx
- src/renderer/src/pages/home/Messages/SelectionBox.tsx
Fix #6331 
修复拖动多选交互体验
https://github.com/user-attachments/assets/8a6c0122-4143-4bd3-a82f-e5186c46adcd
> fix: improve multi-select functionality in Messages and SelectionBox

- src/main/embeddings/EmbeddingsFactory.ts
- src/renderer/src/config/providers.ts
- src/renderer/src/services/KnowledgeService.ts
- src/renderer/src/types/index.ts
After this PR:
Fixes #6142 
```release-note
```
> fix: update dimensions handling in KnowledgeBaseParams

- src/renderer/src/store/messageBlock.ts
- src/renderer/src/utils/__tests__/export.test.ts
- src/renderer/src/utils/export.ts
- src/renderer/src/utils/messageUtils/find.ts
- Refactored message export functions to include citation content in markdown output.
- Introduced a new utility function to extract and format citations from messages.
- Updated related imports and adjusted existing markdown generation logic for improved clarity and maintainability.
修复了导出时引用块丢失的情况
Fixes #5297 
```release-note
```
> feat: enhance citation handling in message export functionality

- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
修复了多模型回答中具有内置搜索能力的模型污染了没有内置搜索能力的模型的情
Fixes #
```release-note
```
> fix: enhance web search recognization in AI providers

- src/renderer/src/components/QuickPanel/view.tsx
> fix: escape special characters in search pattern for improved filtering

- package.json
see discussion in https://github.com/CherryHQ/cherry-studio/pull/5900#issuecomment-2908224326
> chore: remove postinstall script from package.json

- src/renderer/src/components/CustomCollapse.tsx
> feat: improve header styling in CustomCollapse component

- electron.vite.config.ts
yarn dev会报下面的错误
After this PR:
yarn dev不会报错，并且能正常运行
Fixes #6466 
```release-note
```
> fix: cannot run from yarn dev

- src/renderer/src/windows/selection/action/SelectionActionApp.tsx
- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
> feat: integrate custom CSS support in SelectionAssistant

- package.json
- yarn.lock
> fix[SelectionAssistant]: interrupting in terminal apps

- src/renderer/src/assets/styles/scrollbar.scss
调整全局 scrollbar thumb 样式
After this PR:
使用 pointer cursor
Fixes #6572
```release-note
```
> fix(style): global cursor style for scrollbar thumb

- src/renderer/src/components/CodeBlockView/SvgPreview.tsx
修复 `SvgPreview` 拖拽功能
sanitize 内容
Fixes #6491, fixes #6567
```release-note
```
> fix(SvgPreview): dragging and sanitizing

- src/renderer/src/components/CodeBlockView/SvgPreview.tsx
- src/renderer/src/components/CodeToolbar/usePreviewTools.tsx
> refactor(SvgPreview): use shadow dom

- package.json
- yarn.lock
修复了XShell等终端应用可能存在的Ctrl+C问题
大幅提升了PDF Reader的划词能力
> fix(SelectionAssistant): problems in some terminal apps and pdf readers

- src/renderer/src/context/ThemeProvider.tsx
- src/renderer/src/services/StreamProcessingService.ts
思考完成前，思考时间没有正确保存
After this PR:
保存思考时间
Fixes #6647
```release-note
```
> fix: thinking time reset

- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
This PR addresses  `InvalidCharacterError` when `atob` attempts to decode a non-base64 string, such as `placeholder_image_url`, which can occur if image generation fails to return a valid data URL.
> fix(OpenAIProvider): prevent atob error with non-base64 image URLs

- src/main/configs/SelectionConfig.ts
- src/main/services/SelectionService.ts
- predefined filter list adding excel and powerpoint
- predefined filter list is only available in Selected mode, user can use SelectionAssistant in Ctrlkey mode anyway.
> feat(SelectionService): predefined filter list only available in Selected mode

- src/renderer/src/pages/home/Navbar.tsx
改善macos下全屏后导航栏图标位置排布。
After this PR:
Fixes #
```release-note
```
> fix: adjust sidebar icon margins based on fullscreen state

- package.json
- src/renderer/src/components/__tests__/__snapshots__/Scrollbar.test.tsx.snap
- src/renderer/src/pages/home/Markdown/CitationTooltip.tsx
- src/renderer/src/pages/home/Markdown/__tests__/CitationTooltip.test.tsx
- src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
- src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/CitationTooltip.test.tsx.snap
- src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Markdown.test.tsx.snap
- src/renderer/src/pages/home/Messages/Blocks/MainTextBlock.tsx
- src/renderer/src/pages/home/Messages/Blocks/__tests__/MainTextBlock.test.tsx
- src/renderer/src/pages/home/Messages/Blocks/__tests__/ThinkingBlock.test.tsx
- src/renderer/src/pages/home/Messages/Blocks/__tests__/__snapshots__/ThinkingBlock.test.tsx.snap
- src/renderer/src/utils/__tests__/formats.test.ts
- src/renderer/src/utils/__tests__/markdown.test.ts
- src/renderer/src/utils/formats.ts
- src/renderer/src/utils/markdown.ts
补充测试：
- `Markdown`、`CitationTooltip`
- `MainTextBlock`
- `ThinkingBlock`
更新测试：
- `Scrollbar` snapshot
重构代码：
- 在 `MainTextBlock` 中使用 utils 中的 `encodeHTML`
- 简化 `CitationTooltip` 样式，移除 deprecated attribute
修复：
- #6665 
Fixes #
```release-note
```
> test: more unit tests for message rendering

- src/renderer/src/hooks/useMessageOperations.ts
- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/services/TokenService.ts
Before this PR: 编辑消息后，tokens用量未更新
After this PR: 编辑消息后，tokens用量正常更新
Fixes #6580 
```release-note
```
> fix: token usage not updated after editing message

- src/renderer/src/pages/home/Messages/MessageGroup.tsx
“简洁”消息样式，话题在右侧时，把窗口宽度调整到最小，消息会溢出。
`GridContainer` 最小宽度被设置为 `550px`，这个值似乎过大了。
After this PR:
调整 `GridContainer` 最小宽度到 `480px`。
Fixes #
```release-note
```
> fix: prevent message overflow when minimized width

- src/renderer/src/components/app/Sidebar.tsx
> fix: optimize multilingual display of documents

- src/renderer/src/utils/export.ts
After this PR:
Fixes #
```release-note
```
> fix: correct variable name obsidianVault in Obsidian export

- src/renderer/src/assets/styles/container.scss
- src/renderer/src/assets/styles/markdown.scss
- src/renderer/src/components/CodeBlockView/CodePreview.tsx
- src/renderer/src/components/CodeBlockView/index.tsx
- src/renderer/src/components/CodeEditor/index.tsx
- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageSelect.tsx
- 代码块在 bubble style 中宽度不够
#6273 没有真正修复问题，只是限制了最小宽度，相关修改也已经在 [13d440b](https://github.com/CherryHQ/cherry-studio/commit/13d440b0b64974ca9dda146b178ece05a54bf64a#diff-a5409ffa5560d39747fd570157f18059c0a679bbab51c3a101760ce0c900419b) 中回退。
After this PR:
- 修复宽度问题
- revert 之前不必要的样式调整
- 改善 CodeEditor 边框，移除聚焦时的边框
https://github.com/user-attachments/assets/5255fd8e-102b-4bc8-94ee-560cdc96e805
Fixes #6748
```release-note
```
> fix: codeblock overflow in bubble style

- package.json
- src/main/configs/SelectionConfig.ts
- src/main/services/SelectionService.ts
- yarn.lock
修复：
- JetBrains系列IDE崩溃问题
- 远程桌面按键穿透问题
- 游戏模式禁用划词
- 各类PDF软件划词能力
> fix(SelectionAssistant): JetBrains IDEs, Remote desktop, Gaming, PDF views, etc

- src/renderer/src/providers/AiProvider/AnthropicProvider.ts
赋值错误会抛出未捕获错误，导致阻塞topic队列清空，导致topic一直处于loading
Fixes #
```release-note
```
> fix(AnthropicProvider): update usage and metrics handling to prevent TypeError 

- src/renderer/src/providers/AiProvider/OpenAIResponseProvider.ts
- src/renderer/src/services/ApiService.ts
Before this PR: 如 #6767 描述
After this PR: 已修复，但解决方案健壮性可能需要改善
原本API key检查的判断逻辑是先检查流式是否正确响应，如果未正确响应就尝试非流式。实际测试时发现这可能触发429错误，导致抛出异常到外部时反馈给用户的不是真正的问题，而是429错误。不应该假设问题由流式引起，而是需要做一些判断。但是我并不清楚OpenAI的API在什么情况下设置为流式会出问题，总之先随便写了一个判断逻辑。
另外，还没有测试其他供应商的API是否存在同样问题。
Fixes #6767 
The following tradeoffs were made: 
```release-note
```
> fix: OpenAI provider api check doesn't handle error

- src/renderer/src/store/index.ts
- src/renderer/src/store/migrate.ts
After this PR:
解决展示消息Token用量设置的迁移问题
Fixes #
```release-note
```
> hotfix: ensure show token usage setting defaults to true

- src/renderer/src/providers/AiProvider/GeminiProvider.ts
修复gemini-2.5-pro-preview-06-05无法使用的情况
> hotfix: gemini-2.5-pro-preview-06-05 using error

- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
为划词助手的按钮添加过渡效果
Fixes #
```release-note
```
> refactor(SelectionToolbar): add transition effects to action buttons

- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
设置界面划词助手demo可以拖动，像个小红点似的
After this PR:
防止拖动 demo
Fixes #
```release-note
```
> fix(SelectionToolbar): prevent dragging the demo

- src/main/services/ConfigManager.ts
- src/renderer/src/store/selectionStore.ts
> fix(SelectionAssistant): default disabled

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
flex布局会导致高度计算失效
Fixes #6890
```release-note
```
> fix(Inputbar): remove unnecessary flex properties from Inputbar styles

- src/renderer/src/pages/home/Messages/MessageEditor.tsx
- src/renderer/src/pages/settings/AboutSettings.tsx
Before this PR: #6909 原来不是没做，而是bug (= =)
After this PR: 修好了
另外给菜单加了个上边框，看起来舒服一点
Fixes #6909
```release-note
```
> fix: message editor doesn't resize

- src/renderer/src/providers/AiProvider/OpenAIProvider.ts
Before this PR: 如 #6933 所述
After this PR: 修改了api请求，使其符合voyage ai的文档描述
Fixes #6933 
```release-note
```
> fix: voyage ai can't be used on text embedding

- .github/workflows/release.yml
Before this PR:需要手动更新cherry-studio-docs中download.md中的版本号
After this PR:将在所有系统全部构建成功、tag 中不带有 rc 或 pre-release 字样的 release 中自动通知 cherry-studio-docs 更新 download.md 中的版本号
需要 cherry-studio-docs 仓库合并对应的 pr CherryHQ/cherry-studio-docs#66 ，我将在此 pr 被合并后操作。
需要在主仓库的 secrets 中，增加一个 REPO_DISPATCH_TOKEN ，内容需要设置为一个拥有 cherry-studio-docs 仓库 write 权限的账号的 github Personal access tokens (classic) ，并给予 repo 权限。
Fixes #
```release-note
NONE
```
> 增加自动更新文档中版本号的github workflow

- src/main/services/BackupManager.ts
不传长度的话，会创建一个0 kb的文件，再一直写。有些webdav不能创建0 kb的tempfile导致失败。
After this PR:
传长度过去，这些webdav也不会失败了。
有测试过nas的webdav都能正常工作的。
Fixes #6905
```release-note
```
> fix(BackupManager): add content length to WebDAV file upload options

- src/renderer/src/config/models.ts
- src/renderer/src/store/llm.ts
- src/renderer/src/store/migrate.ts
> fix(migrate): old translateModel incorrect

- src/preload/index.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
Before this PR: #6989 
After this PR: 添加了提示词变量的说明
Fixes #6989 
```release-note
```
> feat: add prompt variables description

- src/renderer/src/hooks/useTags.ts
增加了默认状态，防止旧用户无法正常升级
After this PR:
Fixes #
```release-note
```
> fix: fix waring in usetags

- src/renderer/src/pages/knowledge/components/KnowledgeSettingsPopup.tsx
- src/renderer/src/providers/AiProvider/BaseProvider.ts
Before this PR: #3947 不应该修改已存在知识库的嵌入维度，向量数据库需要统一的向量维度
After this PR: 已去除在已有知识库上修改嵌入维度的UI
Fixes #
```release-note
```
> fix: shouldn't edit embedding dimension on existing knowledge base

- src/renderer/src/pages/home/Messages/CitationsList.tsx
在引用界面为每个引用提供了序号，包括知识库和网络搜索
Fixes #7051 
```release-note
```
> feat: add citation index to show

- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageGroup.tsx
Before this PR: [discussion](https://github.com/CherryHQ/cherry-studio/pull/7026#discussion_r2137687970)
After this PR: 已修复横向溢出问题
Fixes #
```release-note
```
> fix: bubble overflow patch

- package.json
- yarn.lock
尽量减少划词助手回退到复制状态时，对用户ctrl+c的影响（划词模式下，任何时候发现ctrl按下即放弃复制）
> fix(SelectionAssistant): reduce Copy conflict

- src/renderer/src/windows/selection/action/SelectionActionApp.tsx
> fix(SelectionAssistant): improve auto-scroll behavior in action window

- src/renderer/src/pages/home/Markdown/Markdown.tsx
- src/renderer/src/pages/home/Markdown/Table.tsx
- src/renderer/src/pages/home/Markdown/__tests__/Markdown.test.tsx
- src/renderer/src/pages/home/Markdown/__tests__/Table.test.tsx
- src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Markdown.test.tsx.snap
- src/renderer/src/pages/home/Markdown/__tests__/__snapshots__/Table.test.tsx.snap
- src/renderer/src/pages/home/Messages/ChatNavigation.tsx
Markdown 表格不支持复制源代码
After this PR:
支持复制源代码
https://github.com/user-attachments/assets/69bba042-b39d-4d1f-b73c-2310232ed3f3
Fixes #7009 
```release-note
```
> feat(Markdown): customize table to support source copying

- src/renderer/src/hooks/useTopic.ts
#6794 增加的动画是由 `startTopicRenaming` 触发的，但是 `startTopicRenaming` 的位置不对，应该放在实际要发生重命名的时候。
`onComplete` 总是会触发重命名动画，而不管是否真的需要重命名。
After this PR:
只在特定情况下触发重命名动画：
- 关闭“自动重命名”并且确实需要更新话题名
- 开启“自动重命名”并且即将发送请求
Fixes #
```release-note
```
> fix: start animation only if the topic should be renamed

- src/main/services/AppUpdater.ts
- Added support for setting the installation directory for the autoUpdater on Windows using NsisUpdater.
- Imported the 'path' module to dynamically determine the installation path based on the executable location.
- This change improves the updater's functionality and ensures a smoother installation experience for Windows users.
如果用户安装的时候选择了其它目录，更新的时候还是会默认安装到user data目录下面去。
After this PR:
如果用户安装的时候选择了其它目录，更新的时候也默认安装其它目录。
Fixes https://github.com/CherryHQ/cherry-studio/issues/7102#issuecomment-2965482120
This checklist is not enforcing, but it's a …
> feat: Enhance AppUpdater for Windows installation directory support

- electron.vite.config.ts
- Modified the Rollup options to disable code splitting and enable inline dynamic imports, ensuring a single file output for the build process. This change optimizes the packaging of the Electron application.
`yarn dev`
After this PR:
循环导入。可以直接都打包到index.js解决。
Fixes #
```release-note
```
> chore(electron.vite.config): update Rollup configuration for single file packaging

- src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
- src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
- src/renderer/src/utils/prompt.ts
{{model_name}}可以正确获取当前助手的模型
Fixes #7177
```release-note
```
> fix: model_name prompt var always use default model

- src/renderer/src/assets/styles/index.scss
之前在 #7026 处理过的样式问题又出现了
https://github.com/CherryHQ/cherry-studio/pull/7026#issuecomment-2958219440
修复了一下
Fixes #
```release-note
```
> fix: remove margin-bottom for loading animation

- .yarn/patches/app-builder-lib-npm-26.0.15-360e5b0476.patch
- yarn.lock
- Updated the resolution and checksum for the app-builder-lib patch in yarn.lock.
- Introduced a new configuration option `excludeReBuildModules` to specify modules to exclude from the rebuild process in configuration.d.ts and scheme.json.
- Adjusted related files to accommodate the new option and ensure proper handling in the rebuild logic.
不支持过滤某些包不要rebuild
After this PR:
支持配置某些包可以rebuild
在electron-builder里面加上配置
Fixes #
Approvers are expected to review this …
> fix: update app-builder-lib patch and add excludeReBuildModules option

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Messages/MessageEditor.tsx
Before this PR: #6931 
After this PR: 原来是编辑已有消息的界面里根本没绑快捷键。现在加上了。
Fixes #6931 
Fixes #7074
```release-note
```
> fix: send message shortcut doesn't work when editing existing message

- src/renderer/src/pages/files/FileList.tsx
- src/renderer/src/pages/files/ImageItem.tsx
- src/renderer/src/pages/files/ImageList.tsx
- 封装了文件页面的图片展示相关组件。(`ImageList`, `ImageItem`）
- 为`ImageItem`添加`loading`状态以解决 #7200 
Fixes #7200 
要单独控制每个图片的加载就需要为每个图片组件单独设置状态，所以封装了图片组件
```release-note
```
> refactor: Encapsulate image display related components

- src/main/services/SelectionService.ts
- 修复Windows 10低版本的工具栏不显示的问题
- 修复工具栏在某些已置顶窗口中被遮盖的问题
> fix(SelectionService): Win10 showing problem & AlwaysOnTop level

- src/renderer/src/config/models.ts
gemini model list 现在多了 `models/` 前缀
After this PR:
正确识别
Fixes #
```release-note
```
> fix: gemini generateImage model detection

- src/renderer/src/aiCore/clients/BaseApiClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
- src/renderer/src/aiCore/middleware/core/McpToolChunkMiddleware.ts
- src/renderer/src/config/models.ts
修复了助手消息可能为空的情况
Fixes #7290
```release-note
```
> fix: update buildSdkMessages to handle undefined output in API clients

- src/main/services/TrayService.ts
> feat: toggle Selection Assistant on tray menu

- src/renderer/src/aiCore/clients/gemini/GeminiAPIClient.ts
- src/renderer/src/config/models.ts
1. Gemini 从 2.0 开始支持内置搜索，联网模型匹配 `gemini-2.`
2. 更新 2.5 Flash Lite 思考预算范围
3. gemini-2.0-flash-exp-image-generation 支持只有文字对话
After this PR:
Fixes #
```release-note
```
> feat: update gemini-2.5 model capabilities and thinking budget

- src/renderer/src/services/ApiService.ts
- Added error handling for tool fetching to log errors and return an empty array if a server fails to respond.
- Changed from Promise.all to Promise.allSettled to ensure all tool fetching attempts are accounted for, filtering out any rejected promises.
过滤出成功的mcptool，而不是当某一个mcp失败时，短路所有toolpromise
Fixes #6303 #6412
```release-note
```
> fix(ApiService): improve error handling when fetching tools from MCP servers

- package.json
- packages/shared/config/languages.ts
- src/renderer/src/utils/__tests__/markdown.test.ts
- src/renderer/src/utils/markdown.ts
- yarn.lock
After this PR:
Fixes #
```release-note
```
> refactor: hard-coded language map

- src/renderer/src/services/AssistantService.ts
Before this PR: Stream output toggle off but displayed on when creating an assistant for the first time
After this PR: Stream output toggle on and displayed on when creating an assistant for the first time
Fixes #7345
> fix(AssistantService): add default settings configuration to assistant initialization

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
Before this PR: Markdown导出显示模型名称设置项文本不正确，见#7366
After this PR: 修复相关i18n文档
Fixes #7366 
```release-note
```
> fix(i18n): fix model name export help text

- src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIBaseClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIResponseAPIClient.ts
Fixes #7383
```release-note
```
> fix: Chat does not work properly when configuring multiple API keys

- src/renderer/src/config/models.ts
重复的模型导致了神秘的自我复制问题，删掉就没事了
Fixes #5279 
Fixes #7098
```release-note
```
> fix: remove duplicated deepseek-v3 in volcengine

- package.json
- packages/shared/config/constant.ts
- src/main/loader/index.ts
- src/main/services/FileStorage.ts
- src/main/utils/__tests__/file.test.ts
- yarn.lock
Before this PR: Can't upload .doc file because officeparser only support .docx filetype
After this PR: Use word-extractor for .doc file
Resolve #7370
> feat(FileStorage): add support for .doc files using word-extractor

- src/renderer/src/services/ApiService.ts
如果对话中打开了思考预算，话题命名也会随着打开思考预算
After this PR:
强制关闭话题命名的思考
Fixes #
```release-note
```
> fix(rename): disable thinking for topic rename

- src/main/mcpServers/sequentialthinking.ts
为@cherry/sequentialthinking的响应添加了thought字段
Fixes #7462 
问题在于提示词方式调用工具不会在上下文中提供输入的参数，而sequentialthinking这个mcp服务器的response中又不包含思考内容，导致添加到上下文中的只有一个不含思考内容的意义不明的结果。
但是，如果想要把调用的params也加入到上下文中的话，要动的地方很多。这个解决方案对修改了原版的sequentialthinking，以满足Cherry Studio的提示词调用需求。
```release-note
```
> feat(mcpServers): Add a thought field to sequential thinking mcp server

- src/renderer/src/store/thunk/messageThunk.ts
重新发送用户消息/编辑后重新发送都会复用缓存的搜索结果，导致关闭网络搜索之后仍然会发送上一次缓存的结果给模型。
After this PR:
重新发送之前，先清除缓存
目前使用了 [keyv-storage](https://github.com/kangfenmao/keyv-storage) 的 `remove`
Fixes #7502
```release-note
```
> fix: clear search cache on resending

- src/renderer/src/windows/selection/action/components/WindowFooter.tsx
从视觉上解决用户可能完全不知道有暂停、重新生成和复制的功能的情况
fix #7521
> feat(SelectionAssistant): actionWindow show footer a while when initial showing and key pressing

- src/renderer/src/pages/settings/SelectionAssistantSettings/SelectionAssistantSettings.tsx
> fix(SelectionAssistant): opacity slider too slow when sliding in settings page

- src/renderer/selectionToolbar.html
- src/renderer/src/assets/styles/selection-toolbar.scss
- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
划词助手工具栏 样式全面可自定义
可通过自定义CSS，来精细调整工具栏外观，包括LOGO的隐藏
包括以下变量（所有变量以 `--selection-toolbar-` 开头）：
``` CSS
// Basic Colors
--color-primary: #00b96b;
--color-error: #f44336;
--selection-toolbar-color-primary: var(--color-primary);
--selection-toolbar-color-error: var(--color-error);
// Toolbar
--selection-toolbar-height: 36px; // default: 36px   max: 42px
--selection-toolbar-font-size: 14px; // default: 14px
--selection-toolbar-logo-display: flex; // values: flex | none
--selection-toolbar-logo-size: 22px; // default: 22px
--selection-toolbar-logo-margin: 0 0 0 5px; // default: 0 0 05px
// DO NOT MODIFY THESE VALUES, IF YOU DON'T KNOW WHAT YOU ARE DOING
--selection-toolbar-padding: 2px 4px 2px 2px; // default: 2px 4px 2px 2px
--selection-toolbar-margin: 2px 3px 5px 3px; // default: 2px 3px 5px 3px …
```
> refactor(SelectionAssistant): make all Toolbar CSS variables customizable

- src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
- src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
- src/renderer/src/pages/home/Messages/Blocks/__tests__/__snapshots__/ThinkingBlock.test.tsx.snap
- src/renderer/src/pages/home/Messages/CitationsList.tsx
修复 Anthropic 模型请求忽略了知识库和网络搜索引用内容的问题
修复前：
修复后：
> Fix anthropic request cannot handle webSearch and knowbase references

- src/renderer/src/config/models.ts
- Added a check to the isReasoningModel function to return false for embedding models, ensuring correct model classification.
After this PR:
Fixes #
```release-note
```
> fix(models): update isReasoningModel function to exclude embedding models

- src/renderer/src/pages/home/Messages/MessageGroupModelList.tsx
- src/renderer/src/utils/motionVariants.ts
增强多模型回答时“标签”样式的反馈
多模型回答时，“标签”样式下一次只能看到一条消息，不切换没法知道其他模型是否回答完毕。
After this PR:
正在回答中的模型 avatar 会有呼吸效果。
https://github.com/user-attachments/assets/51ba86c6-3d1e-4130-bacd-167f4a0af03b
Fixes #
```release-note
```
> feat(MentionedModels): improve feedback for MessageGroupModelList

- src/renderer/src/components/Selector.tsx
- src/renderer/src/pages/settings/ModelSettings/ModelSettings.tsx
1、修复选择器没有显示选中值问题
2、优化模型设置的选择器箭头
After this PR:
> fix(Selector): Fix the issue with the Selector component being selected.

- src/renderer/src/config/models.ts
- Adjusted regex for visionAllowedModels and DOUBAO_THINKING_MODEL_REGEX to allow for optional suffixes.
- Enhanced isFunctionCallingModel and isDoubaoThinkingAutoModel functions to check both model.id and model.name for better matching.
使用下面几个模型测试
doubao-seed-1-6-flash-250615
doubao-seed-1.6-250615
doubao-seed-1.6
doubao-seed-1.6-thinking
Fixes #7619
```release-note
```
> fix(models): update regex patterns for Doubao models and enhance function checks

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
“多选”按钮没有用 lucide，和其他按钮没有对齐
After this PR:
Fixes #
```release-note
```
> fix(Menubar): icon for multi select

- electron-builder.yml
没有linux deb包
After this PR:
有linux deb包。
目前在debian gnome上测试了下deb，没有发现问题。
Fixes #
```release-note
```
> feat: support linux deb

- src/renderer/src/aiCore/middleware/feat/ImageGenerationMiddleware.ts
- Replaced direct API call for reading binary images with FileManager's readBinaryImage method to streamline image handling in the ImageGenerationMiddleware.
After this PR:
Fixes #7670 https://github.com/CherryHQ/cherry-studio/issues/7473#issuecomment-3002409595
```release-note
```
> fix(ImageGenerationMiddleware): read image binary data

- package.json
打包后程序跑不起来
After this PR:
打包后程序可以跑起来
Fixes #
```release-note
```
> chore(package): add opendal dependency to package.json

- src/main/services/WindowService.ts
…indow configuration
目前这个配置我看其它app很多也不开启的，看起来并不会提升多少性能。还有一点，这个删除后，放后台内存会减少很多。
Fixes #
```release-note
```
> fix(WindowService): remove backgroundThrottling option for improved window configuration

- src/main/services/WindowService.ts
disable main window的backgroundThrottling 
使用了几个小时，没有发现问题。
Fixes #
```release-note
```
> fix(WindowService): remove backgroundThrottling option for cleaner window configuration

- package.json
- yarn.lock
electron35.4到 electron35.6期间有修复一些crash。
https://releases.electronjs.org/release/compare/v35.4.0/v35.6.0
Fixes #
```release-note
```
> chore: update electron dependency to version 35.6.0 in package.json and yarn.lock

- src/renderer/src/pages/home/Messages/MessageMenubar.tsx
添加对relatedUserMessageBlocks为空的检查，避免后续逻辑报错
https://github.com/CherryHQ/cherry-studio/pull/7314#issuecomment-3026006952
Fixes #
```release-note
```
> fix(MessageMenubar): Add check for empty relatedUserMessageBlocks to prevent errors

- .vscode/settings.json
主要是我自己给用户设置里面设置了`organizeImports: 'explicit`，但是项目里用的是eslint的simple-import-sort插件实现导入整理，这两种排序的规则有时会冲突，我每次都得手动在工作区禁用这个设置才能行，很麻烦。
把`organizeImports`禁用了也还能用eslint的fixAll来解决导入整理。
Fixes #
```release-note
```
> chore: Disable auto-organize imports on save

- scripts/update-i18n.ts
更新 `update-i18n` 脚本，把 key, url, model 都做成参数
Fixes #
```release-note
```
> chore: update i18n script

- .github/dependabot.yml
移除 dependabot 的依赖更新规则
Fixes #
```release-note
```
> chore: remove dependency updates

- src/renderer/src/pages/home/Messages/MessageGroup.tsx
|Before | After 1 | After 2 |
| --- |---- | --- |
|  ![CleanShot 2025-07-04 at 11 08 03](https://github.com/user-attachments/assets/4557d608-2774-4bb6-b380-80678883beb3) |  ![CleanShot 2025-07-04 at 11 10 12](https://github.com/user-attachments/assets/672d8056-1611-45bd-80d4-24dc83d0278c) |  ![CleanShot 2025-07-04 at 11 07 51](https://github.com/user-attachments/assets/4b217f77-9b63-4ab3-a57e-9ecaf32dc194) |
> feat(message-group): improve layout style

- src/renderer/src/pages/home/Messages/MessageGroup.tsx
> fix(message-group): revert grid layout to use min-width

- src/renderer/src/config/models.ts
- Changed the glm-4 model entry to use a regex pattern for better flexibility in version matching, allowing for optional version numbers and suffixes.
After this PR:
Fixes #7777 
```release-note
```
> fix(models): update glm-4 model regex for improved matching

- src/renderer/src/aiCore/middleware/feat/ThinkingTagExtractionMiddleware.ts
After this PR:
Fixes #7823 #7762
```release-note
```
> fix: qwen3 empty think block

- src/renderer/src/pages/settings/MCPSettings/McpSettings.tsx
Before this PR: #7857 
After this PR: 现在点击保存按钮只会在MCP服务器已启动的情况下重启服务器，在未启动的情况下仅保存配置。
Fixes #7857
```release-note
```
> fix(MCPSettings): ensure save button only restarts MCP server if it is running

- src/renderer/src/config/models.ts
- src/renderer/src/pages/home/Inputbar/ThinkingButton.tsx
After this PR:
Fixes #
```release-note
```
> fix: model recognize

- .github/workflows/dispatch-docs-update.yml
- .github/workflows/release.yml
Before this PR:release工作流编译完成后立刻根据版本号判断是否为正式版，如果是，发送更新版本号的信号
After this PR:将根据github release 中的操作决定是否触发
更健壮地处理版本号没有标注pre-release的非正式版
```release-note
NONE
```
> 使自动更新版本号更健壮

- src/renderer/src/store/mcp.ts
参考`@modelcontextprotocol/server-filesystem`，为`@cherry/filsystem`添加了默认参数。
Fixes #
```release-note
```
> feat(mcp): Add default args for built-in file system MCP server

- src/renderer/src/store/index.ts
- src/renderer/src/store/migrate.ts
> fix(store): fix store migrate and version

- src/main/services/ProtocolClient.ts
- src/main/services/urlschema/handle-providers.ts
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
在macOS上， app最小化，或者hide的状态的时候，调用url scheme不会把app show到前台来。
After this PR:
在macOS上， app最小化，或者hide的状态的时候，调用url scheme可以把app show到前台来。
Fixes #
```release-note
```
> fix: cannot show window in mini and hide status

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
> fix(Inputbar): update resizeTextArea call to improve functionality

- src/renderer/src/config/models.ts
After this PR:
Fixes #
```release-note
```
> feat(models): support Grok4

- package.json
- src/main/services/SelectionService.ts
- src/preload/index.ts
- src/renderer/src/windows/selection/action/SelectionActionApp.tsx
- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
- yarn.lock
> fix(SelectionAssistant): [macOS] show actionWindow on fullscreen app

- src/main/knowledage/embeddings/Embeddings.ts
- src/main/knowledage/embeddings/EmbeddingsFactory.ts
- src/main/knowledage/embeddings/VoyageEmbeddings.ts
- src/main/knowledage/embeddings/utils.ts
- src/renderer/src/aiCore/clients/openai/OpenAIBaseClient.ts
修复了VoyageEmbeddings使用float作为编码格式导致的bad request
修复了VoyageEmbeddings传入dimensions导致请求中含有output_dimensions字段导致的bad request
Fixes #8018
```release-note
```
> fix: VoyageEmbeddings 

- packages/shared/IpcChannel.ts
- src/main/ipc.ts
- src/main/services/FileStorage.ts
- src/preload/index.ts
- src/renderer/src/hooks/useKnowledge.ts
- src/renderer/src/pages/knowledge/items/KnowledgeFiles.tsx
> feat: add upload file

- src/renderer/src/utils/oauth.ts
Add invite code for PPIO billing page links.
```release-note
Add invite code for PPIO billing page links.
```
> fix: fix ppio oauth links

- resources/scripts/install-bun.js
- resources/scripts/install-uv.js
- 添加bun/uv安装脚本的返回值
- 修复原错误无法向上传递的问题
- 修复发生错误时用户收不到错误信息的问题
> fix(install): update return codes for bun and uv installation scripts

- .gitignore
排除更多本地设置文件
- claude code
- gemini cli
- trae
After this PR:
Fixes #
```release-note
```
> chore(gitignore): exclude more AI editor settings

- src/renderer/src/pages/translate/TranslatePage.tsx
| Before | After |
| ---- | ---- |
|  <img width="1582" height="510" alt="image" src="https://github.com/user-attachments/assets/79d20c26-0464-41e5-9c02-4159b586f1b0" /> | <img width="3152" height="2068" alt="CleanShot 2025-07-11 at 14 56 55" src="https://github.com/user-attachments/assets/16c87163-6d6e-4958-acdf-8782ff0af76b" /> |
> feat: improve translate history style

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/settings/MCPSettings/McpTool.tsx
修复 McpTool 中 tools 表格不能适应窗口大小变化的问题
窗口变宽时表格变宽，窗口收缩时表格不跟着收缩。
这是因为开启了 antd table 的 sticky header，这个功能有点问题，已经移除了。
相关讨论见：https://github.com/ant-design/ant-design/issues/36599
After this PR:
表格跟随窗口收缩
Fixes https://github.com/CherryHQ/cherry-studio/pull/8007#issuecomment-3056567780
```release-note
```
> fix: table resizing in mcp tool setting

- src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/store/thunk/messageThunk.ts
- src/renderer/src/types/sdk.ts
- Added support for incremental output in AnthropicAPIClient by introducing TEXT_START and THINKING_START chunk types.
- Updated OpenAIAPIClient to conditionally enable incremental output for specific models.
- Modified messageThunk to handle updated smartBlockUpdate calls with an isComplete parameter for better state management.
- Introduced incremental_output parameter in ReasoningEffortOptionalParams type for enhanced configuration options.
After this PR:
Fixes #8058
This checklist is not enforcing, but it's a reminder of items that could be relevant …
> feat: enhance Anthropic and OpenAI API clients with incremental output support

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/utils/mcp-tools.ts
在兼容模式下处理mcp工具调用响应时，不再是处理为数组格式，而是处理为字符串格式。
考虑到应该只有OpenAI类型的provider可能需要开启兼容模式，现在只改了`OpenAIApiClient`。
Fixes https://github.com/CherryHQ/cherry-studio/issues/7828#issuecomment-3051083805
```release-note
```
> fix(openai): add compatibility mode for handling tool call responses

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
修复了delta为空但是finishReason可能存在的情况
Fixes #8153
> fix: openai api client

- src/main/services/MCPService.ts
添加了MCPService 接收通知更新对应list和其他追踪
Fixes #8173 
Fixes #8172 
After this PR:
Fixes #
```release-note
```
> feat(MCPService):Add notification handlers and clear cache for MCPService

- src/renderer/src/config/constant.ts
- src/renderer/src/context/ThemeProvider.tsx
> fix: set os attribute correctly to body

- src/main/services/urlschema/handle-providers.ts
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- Introduced a new ParseData function to decode and parse base64 encoded data from the URL parameters.
- Added error handling to log when data is null or invalid, improving robustness of the handleProvidersProtocolUrl function.
After this PR:
Fixes #
```release-note
```
> feat: add data parsing functionality in handleProvidersProtocolUrl

- src/renderer/src/aiCore/clients/ApiClientFactory.ts
- src/renderer/src/aiCore/clients/__tests__/ApiClientFactory.test.ts
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
- src/renderer/src/utils/index.ts
特殊 ID 客户端创建
- aihubmix：验证创建 AihubmixAPIClient
- new-api：验证创建 NewAPIClient
- ppio：验证创建 PPIOAPIClient
标准类型客户端创建
- openai：验证创建 OpenAIAPIClient
- azure-openai：验证创建 OpenAIResponseAPIClient
- openai-response：验证创建 OpenAIResponseAPIClient
- gemini：验证创建 GeminiAPIClient
- vertexai：验证创建 VertexAPIClient
- anthropic：验证创建 AnthropicAPIClient
边界情况和优先级测试
- 未知类型处理：验证未知类型默认创建 OpenAIAPIClient
- 最小配置测试：测试空字符串等极简配置的处理
- ID 优先级：验证特殊 ID（如 aihubmix）优先于 type 字段的处理逻辑
- OpenAI 兼容判断：验证 openai、azure-openai、unknown 等类型返回 true
- 非 OpenAI 类型：验证 anthropic、gemini 类型返回 false
- 默认行为：验证除 anthropic 和 gemini 外的所有类型都被视为 OpenAI 兼容
> test: add comprehensive tests for ApiClientFactory

- src/renderer/src/components/ThinkingEffect.tsx
- src/renderer/src/pages/home/Messages/Blocks/ThinkingBlock.tsx
- src/renderer/src/pages/home/Messages/Blocks/__tests__/__snapshots__/ThinkingBlock.test.tsx.snap
- src/renderer/src/windows/mini/chat/components/Message.tsx
1、优化思考效果的大小；
2、修复快捷助手消息样式错误问题；
> refactor(ThinkingEffect): optimize thinking effect

- src/renderer/src/components/ThinkingEffect.tsx
> refactor(ThinkingEffect): 思考结束时收起思考效果

- src/renderer/src/config/models.ts
support vertex websearch
fixes: #8210
> feat: vertexai websearch support

- eslint.config.mjs
- src/main/services/LoggerService.ts
- src/renderer/src/services/LoggerService.ts
- 添加eslint规则，使用console.xxx将会发出提示，但不禁止
- 开发模式终端日志打印时间中去掉年月日，简化显示
- fix：删除之前的开发遗留代码
> fix[Logger]: update ESLint configuration

- src/renderer/src/config/models.ts
- src/renderer/src/config/providers.ts
After this PR:
Fixes #
```release-note
```
> feat: update provider.ts, add models 

- src/main/ipc.ts
- src/main/utils/file.ts
portable exe修改数据目录后，relaunch app后， 不能启动起来，并且每次升级后数据目录都会改回原来默认的位置
After this PR:
portable exe relaunch成功，并且升级后不会，只要新的portable exe还在原来的安装目录下面，数据目录就不会再变化。
Fixes #
```release-note
```
> fix(ipc): add support for portable executable paths on Windows

- src/renderer/src/pages/settings/MCPSettings/AddMcpServerModal.tsx
- src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
从 JSON 导入 MCP 时，没有检查 `tags` 类型，类型不匹配导致渲染失败。
进入 MCP 设置页面就会崩溃
After this PR:
- 补充类型检查
- 对于已经坏了的配置，遇到 tag 就返回 null
Fixes #8254
```release-note
```
> fix(AddMcp): mismatched mcp tag type

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/aiCore/index.ts
- src/renderer/src/aiCore/middleware/core/McpToolChunkMiddleware.ts
- src/renderer/src/aiCore/middleware/core/TextChunkMiddleware.ts
- src/renderer/src/aiCore/middleware/feat/ThinkingTagExtractionMiddleware.ts
- src/renderer/src/aiCore/middleware/feat/ToolUseExtractionMiddleware.ts
- src/renderer/src/services/ApiService.ts
After this PR:
包含`tool_call`的chunk，其`delta.content`可能为`null`，没有考虑进去，导致被跳过了。
Fixes #8275 
Fixes #8290 
Fixes #8258
Fixes #8273
```release-note
```
> fix: get empty response when using MCP by functional method

- src/main/services/MCPService.ts
这块代码最近的提交是统一日志管理，但是这个Set up notification handlers的逻辑被被拷贝了
After this PR:
Set up notification handlers 执行一次
Clear cache 执行一次
Fixes #
```release-note
```
> fix[McpService]: fix NotificationHandlers code duplicates

- src/main/services/ProxyManager.ts
- src/renderer/src/pages/settings/GeneralSettings.tsx
获取系统代理有时候会失败，有时候可能是代理软件还没有开，后面再开的，就会导致获取不到，就不再monitor，会导致后面代理软件开了也打不开。
After this PR:
没有获取到系统代理的url，也需要一直monitor。
Fixes #8329 #8316
```release-note
```
> fix: improve proxy configuration handling and logging in ProxyManager

- src/preload/index.ts
- src/renderer/src/components/ObsidianExportDialog.tsx
- src/renderer/src/pages/settings/DataSettings/ObsidianSettings.tsx
原obsidian preload api放置不规范，做出调整（from window.obsidian to window.api.obsidian
> fix[PreloadAPI]: change Obsidian api from global window to window.api

- src/renderer/src/config/models.ts
添加对qwen-plus-0714和qwen-turbo-0715模型的支持
Fixes https://github.com/CherryHQ/cherry-studio/issues/8344#issuecomment-3100302315
```release-note
```
> fix(models): support new qwen3 model

- src/renderer/src/pages/home/Messages/MessageEditor.tsx
调整 `MessageEditor` 样式：
- 移除自定义 `resizeTextArea`，使用 `autoSize`
- 有多个 block 时，在多个编辑区域之间增加间距
https://github.com/user-attachments/assets/51f1405e-d08f-43a5-aa46-dee5ef6ab1fe
Fixes #8324 
```release-note
```
> refactor(MessageEditor): improve editor style

- src/renderer/src/hooks/useSmoothStream.ts
- src/renderer/src/pages/home/Markdown/Markdown.tsx
fix: https://github.com/CherryHQ/cherry-studio/pull/8070
> fix(useSmoothStream): remove unnecessary comments and markdown displayedContent

- package.json
- src/main/configs/SelectionConfig.ts
- yarn.lock
- [macOS] shift+click行为优化，finder加入黑名单 fix #8343 
- [Windows] 剪切板模式的鼠标检测优化，dpi优化支持Windows 7
> fix[SelectionAssistant]: shift+click behavior in macOS and clipboard behavior in Windows

- src/main/mcpServers/dify-knowledge.ts
- src/main/mcpServers/filesystem.ts
- src/renderer/src/aiCore/clients/anthropic/AnthropicAPIClient.ts
- src/renderer/src/utils/mcp-tools.ts
之前直接把zodschema传入了jsonschema没有做转换
Fixes #8439
> fix(inputSchemas): convert input schemas to JSON schema format for consistency across DifyKnowledgeServer and FileSystemServer

- src/renderer/src/aiCore/middleware/core/ThinkChunkMiddleware.ts
- Removed the reasoning check from the ThinkChunkMiddleware to streamline the processing logic.
- This change enhances the middleware's efficiency by focusing on handling streams directly without the reasoning condition.
这样的话在正则判断失效之后，中间件才能正常起作用
Fixes: #8503  #8500
> refactor(ThinkChunkMiddleware): remove reasoning check for improved logic clarity

- .gitignore
After this PR:
Fixes #
```release-note
```
> chore: ignore qwen-code settings

- src/renderer/src/aiCore/index.ts
- src/renderer/src/pages/paintings/AihubmixPage.tsx
- src/renderer/src/pages/paintings/config/aihubmixConfig.tsx
After this PR:
Fixes #
```release-note
```
> fix: aihubmix provider generate image logic

- src/main/services/MCPService.ts
> fix: call tool bug

- package.json
- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- yarn.lock
https://github.com/CherryHQ/cherry-studio/issues/8531#issuecomment-3119814043
修复Mistral Provider中传入的多余键值
> fix: #8531

- src/renderer/src/hooks/useAssistant.ts
- src/renderer/src/pages/home/Tabs/AssistantsTab.tsx
- src/renderer/src/pages/home/Tabs/components/AssistantItem.tsx
- src/renderer/src/store/assistants.ts
现在复制助手时，新助手将会出现在原助手后，而不是末尾
Fixes #8549
```release-note
```
> feat(assistants): place copied assistant after the original one

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
现在对于百炼官方的qwen3模型，不再会添加/no_think后缀。
理由：
1. 百炼平台的qwen3模型支持`enable_thinking`参数，不需要添加指令
2. 我真的受不了了
Fixes #
```release-note
```
> fix: no `/no_think` for qwen3 anymore if provider is dashscope

- src/renderer/src/components/EmojiPicker/index.tsx
- src/renderer/src/components/MinApp/WebviewContainer.tsx
- src/renderer/src/components/ModelList/EditModelsPopup.tsx
- src/renderer/src/components/Popups/AddAssistantPopup.tsx
- src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
- src/renderer/src/components/Popups/TextEditPopup.tsx
- src/renderer/src/components/Selector.tsx
- src/renderer/src/components/app/PinnedMinapps.tsx
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Inputbar/WebSearchButton.tsx
- src/renderer/src/pages/home/Messages/ChatFlowHistory.tsx
- src/renderer/src/pages/home/Messages/MessageEditor.tsx
- src/renderer/src/pages/home/Messages/MessageTools.tsx
清理setTimeout和事件监听器以避免内存泄漏
优化useEffect中的异步操作清理逻辑
Fixes #
```release-note
```
> perf: part of memory leak

- src/renderer/src/pages/settings/ApiServerSettings/ApiServerSettings.tsx
- src/renderer/src/pages/settings/SettingsPage.tsx
- src/renderer/src/pages/settings/index.tsx
> fix: apiserver display

- src/renderer/src/aiCore/middleware/__tests__/utils.test.ts
- createErrorChunk - 错误对象标准化处理
- capitalize - 字符串首字母大写
- isAsyncIterable - 异步可迭代对象判断
- 正常使用场景
- 边界条件处理（null、undefined、空字符串等）
- 各种数据类型支持
- 错误场景处理
> test: add tests for aiCore/middleware/utils

- src/renderer/src/components/CustomCollapse.tsx
- src/renderer/src/components/ModelList/EditModelPopup.tsx
- src/renderer/src/components/ModelList/ManageModelsList.tsx
- src/renderer/src/components/ModelList/ManageModelsPopup.tsx
- src/renderer/src/components/ModelList/ModelList.tsx
- src/renderer/src/components/ModelList/ModelListGroup.tsx
- src/renderer/src/components/ModelList/index.ts
- src/renderer/src/components/ModelList/utils.ts
- src/renderer/src/pages/settings/ApiServerSettings/ApiServerSettings.tsx
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
提高“模型服务”界面响应性
**Before this PR**:
当服务商模型很多时会很卡，比如说从 Cherry Studio 自己的端点获取所有模型之后。
模型列表：
https://github.com/user-attachments/assets/919c766e-1cdc-42dc-b6f0-176559bc662f
管理模型界面：
https://github.com/user-attachments/assets/2881796e-0186-428b-adab-b10355886210
**After this PR**:
- 增加 loading indicator，改善服务商模型列表切换体验
- 模型列表使用虚拟滚动
模型列表：
https://github.com/user-attachments/assets/82d14c1e-5100-4672-8e33-54640b27aa19
管理模型界面：
https://github.com/user-attachments/assets/2ffc9f76-81af-496b-b675-c4a165c642a2
Fixes #
管理模型界面用了一个虚拟列表而不是每组一个，然后加上 sticky header，看起来简洁点。
相应地，没有使用 CustomCollapse，而是自定义了一个简单的折叠操作。
If this PR introduces breaking changes, please describe the changes and …
> perf(ModelList): provider settings and model list responsiveness

- src/renderer/src/pages/agents/components/AddAgentPopup.tsx
- src/renderer/src/pages/settings/ModelSettings/DefaultAssistantSettings.tsx
After this PR:
Fixes #
```release-note
```
> fix: do not exit on emoji picker

- src/renderer/src/pages/home/Messages/Message.tsx
- src/renderer/src/pages/home/Messages/MessageHeader.tsx
- src/renderer/src/pages/home/Messages/SelectionBox.tsx
1. 如果是多选模式，添加 label 包裹 message，这样点击 message 的话 checkbox 的值也会随着改变，而不需要单独去点击 checkbox
2. 修复多选模式下清除上下文也会被算作一条选中的消息
> feat: add multi-select mode wrapper for message component

- src/renderer/src/utils/__tests__/prompt.test.ts
- src/renderer/src/utils/prompt.ts
思考工具提示词插入在system prompt会影响模型输出
Fixes #
```release-note
```
> fix(prompt): remove think tool

- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
Before this PR: https://github.com/CherryHQ/cherry-studio/pull/8739#issuecomment-3143555578
After this PR:
Fixes #
```release-note
```
> fix(Inputbar): input bar auto focus

- src/renderer/src/config/models.ts
> fix(models): add 'qwen-plus-latest' entry and update regex patterns for model token limits

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/aiCore/index.ts
- src/renderer/src/aiCore/middleware/feat/ThinkingTagExtractionMiddleware.ts
- src/renderer/src/services/__tests__/ApiService.test.ts
After this PR:
Fixes #8738 
```release-note
```
> fix(OpenAIApiClient): fix multiple reasoning content handling

- src/renderer/src/components/Tab/TabContainer.tsx
- src/renderer/src/components/app/Sidebar.tsx
- src/renderer/src/pages/settings/DisplaySettings/DisplaySettings.tsx
* refactor: replace setTheme with toggleTheme and update theme state management
* feat: add Monitor icon for additional theme state in both components
system theme切换没有了，
After this PR:
加上system theme，并且使用monitor icon
Fixes #
```release-note
```
> refactor: update theme handling in TabContainer and Sidebar components

- src/renderer/src/services/ApiService.ts
- src/renderer/src/utils/abortController.ts
1. 从原issue可以观察到是r1模型一直在转圈，我判断是r1返回结果太慢了才这样，因为现在的逻辑是必须等待所有内容生成完毕才检查通过。然而，实际上连通性检查完全没有必要这样做。对于流式输出而言，只要接收到一个chunk就可以判断检查通过了。这个改动可以大幅增加健康检测的速度。
2. 添加了超时机制保底，确保不会无限转圈
before:
after:
Fixes #8798
```release-note
```
> perf(ApiService): speed up api check

- package.json
- src/renderer/src/assets/styles/markdown.scss
- src/renderer/src/pages/home/Markdown/Markdown.tsx
- yarn.lock
| BEFORE | AFTER |
|---|---|
|<img width="551" height="631" alt="image" src="https://github.com/user-attachments/assets/6f3900e9-1589-4101-880e-6abf2318b9f0" />|<img width="546" height="682" alt="image" src="https://github.com/user-attachments/assets/932fe906-d72c-41c4-9f1f-e3ae2120b7b2" />|
Fixes #
```release-note
```
> feat(Markdown): enable github markdown alert

- src/main/services/WindowService.ts
Close: #8822 
https://github.com/user-attachments/assets/f5ad34f8-3a7c-4856-99a0-52ead68a5191
> feat: mini window state management

- src/renderer/src/config/models.ts
添加Step-1o和Step-1v到视觉允许模型列表
新增isStepReasoningModel函数判断Step系列推理模型
After this PR:
Fixes #8851 
```release-note
```
> feat(model): support step models

- src/renderer/src/aiCore/clients/AihubmixAPIClient.ts
After this PR:
Fixes #
```release-note
```
> feat(aihubmix): support gpt oss models

- src/renderer/src/config/models.ts
添加了模型Logo和能力判断
Fixes #
```release-note
```
> feat: support gpt-oss

- src/renderer/src/components/DraggableList/virtual-list.tsx
- src/renderer/src/components/__tests__/__snapshots__/DraggableVirtualList.test.tsx.snap
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- 搜索时禁用了拖动
- 样式调整
Fixes #8904 
```release-note
```
> fix: drag providers caused crash

- src/renderer/src/i18n/label.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/pages/settings/MCPSettings/BuiltinMCPServersSection.tsx
- src/renderer/src/store/mcp.ts
- src/renderer/src/types/index.ts
- 修复了函数对象无法序列化的问题
- 重构了i18n文本获取方法
Fixes #
```release-note
```
> fix(mcp): builtin mcp objects cannot be serialized

- src/renderer/src/pages/settings/ProviderSettings/ModelList/ManageModelsPopup.tsx
顺便移除了 deprecated 属性
After this PR:
Fixes #8909 
```release-note
```
> fix: lower popup height

- src/renderer/src/pages/home/Chat.tsx
- src/renderer/src/pages/home/Messages/Messages.tsx
重构消息组件结构，将ChatNavigation组件从Messages.tsx移动到Chat.tsx中
Fixes #8931 
```release-note
```
> fix: input bar covers chat nav buttons

- src/renderer/src/aiCore/clients/openai/OpenAIBaseClient.ts
- src/renderer/src/config/providers.ts
修复 GitHub Models 的 API 地址配置错误，并调整基础路径以适配其特殊接口结构
Fixes #
```release-note
```
> fix(providers): update GitHub Models api url

- src/main/services/SelectionService.ts
> fix(SelectionService): check screen edge to prevent toolbar overlay selection

- src/renderer/src/aiCore/clients/openai/OpenAIBaseClient.ts
- src/renderer/src/config/providers.ts
github models 接口更新过了，不应该再用 name
api baseurl 顺便也修复了
Fixes #
```release-note
```
> fix(github models): get id instead of name

- src/renderer/src/pages/translate/TranslatePage.tsx
修复了从store获取过时的翻译内容导致缺少部分内容的问题。可能是节流更新导致的更新不及时。
Fixes #
```release-note
```
> fix(translate): don't use stale state when saving translate history

- src/renderer/src/aiCore/clients/anthropic/AnthropicVertexClient.ts
- src/renderer/src/aiCore/index.ts
anthropicvertexapiclient没有实现获取真正类型的方法，会导致监听不到原始的消息
After this PR:
实现这个方法
Fixes  #8932
> feat(AnthropicVertexClient): add client compatibility type method

- src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
In the column settings, due to different heights, there are differences in the display of background colors. This time, in the data setting column of PR, the heights of each module are unified to ensure a uniform background color and enhance the UI aesthetics.
After this PR:
Fixes #
```release-note
```
> fix: set the inconsistency of column background color issue

- src/renderer/src/config/providers.ts
七牛云提供商不支持developer role
Fixes #9097
```release-note
```
> fix(providers): qiniu doesn't support developer role

- src/renderer/src/config/models.ts
> fix: modelname

- src/main/services/AppUpdater.ts
current version: 1.5.4
The latest version is 1.5.6
The rc version is 1.5.6-rc.1
打开test plan后会先升级到1.5.6-rc.1，再升级到1.5.6
After this PR:
打开test plan后直接升级到1.5.6，而不需要经过两次升级。
Fixes #
```release-note
```
> refactor(AppUpdater): streamline release version fetching and improve update logic

- src/renderer/src/pages/paintings/DmxapiPage.tsx
- src/renderer/src/pages/paintings/config/DmxapiConfig.ts
After this PR:
新增图片编辑模型seededit-3.0
Fixes #
```release-note
```
> feat(DMXAPI): new add painting seededit

- src/renderer/src/components/DraggableList/__tests__/DraggableList.test.tsx
- src/renderer/src/components/DraggableList/list.tsx
- src/renderer/src/components/DraggableList/virtual-list.tsx
拖拽时如果 source 和 target 相同，避免执行 update。
有些组件的 update 很重，比如 McpServersList，拖拽时位置没有变化时也执行了不必要的 update。
After this PR:
Fixes #
```release-note
```
> perf(DraggableList): skip update if dnd to the same position

- src/renderer/src/components/Preview/utils.ts
- src/renderer/src/utils/image.ts
修复 mermaid 渲染的宽度问题和文字丢失问题
After this PR:
Fixes #
```release-note
```
> fix: svg rendering

- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
添加工具提示以解释按钮功能，提升用户体验
Fixes #
```release-note
```
> feat(ProviderSetting): add tooltip for api options

- src/main/services/AppUpdater.ts
- src/renderer/src/services/ApiService.ts
- src/renderer/src/services/messageStreaming/callbacks/citationCallbacks.ts
After this PR:
Fixes #
```release-note
```
> feat: 同步百炼服务器功能

- package.json
- yarn.lock
upgrade to 1.0.10 to fix and improve validation for selected text range to handle empty strings and ensure valid extraction
> fix(SelectionHook): improve validation for selected text range to handle empty strings and ensure valid extraction

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/config/models.ts
在OpenAIAPIClient中添加对智谱AI特殊token的处理逻辑，避免不需要的token被输出
Fixes #9321
```release-note
```
> feat(openai): handle special tokens for zhipu api

- src/renderer/src/assets/styles/animation.scss
- src/renderer/src/pages/home/Messages/Message.tsx
定位消息时使用更加平滑的动画
After this PR:
Fixes #
```release-note
```
> refactor: improve locate highlight animation

- src/main/config.ts
After this PR:
Fixes #
```release-note
```
> fix: change title bar overlay color for windows

- src/renderer/src/pages/home/Markdown/CodeBlock.tsx
- src/renderer/src/pages/home/Markdown/__tests__/CodeBlock.test.tsx
- src/renderer/src/utils/markdown.ts
HTML 代码块结束检测：
- 不在流式响应中，或者
- 包含 closed fence
这个 PR 补充 closed fence 的判定逻辑，避免根据 html 代码内容判定结束。
重构 html 代码块时移除了根据代码内容判定结束与否的逻辑，只保留了 `isStreaming` 判定。
https://github.com/user-attachments/assets/e7bd8c89-49cd-4a88-93ec-341b70960f6a
After this PR:
补充 closed fence 判定。
https://github.com/user-attachments/assets/7f9ae7cb-39ca-4b91-8d43-a6c696661657
Fixes #
```release-note
```
> refactor(CodeBlock): closed fence detection for html

- .github/workflows/pr-ci.yml
- src/main/config.ts
- src/main/services/NotificationService.ts
细化 pr workflow，把 test:lint 提前避免跳过问题
After this PR:
Fixes #
```release-note
```
> chore(ci): refine pr ci steps

- src/renderer/src/components/Tab/TabContainer.tsx
- src/renderer/src/windows/mini/home/HomeWindow.tsx
- src/renderer/src/windows/selection/action/components/ActionGeneral.tsx
- src/renderer/src/windows/selection/action/components/ActionUtils.ts
这个问题在快捷助手也存在。
- 确保assistant的settings在设置streamOutput时不会意外覆盖掉原有的设置
- 显式关闭部分功能，因为这些功能无法正常运作。
- 知识库功能虽然可以使用，但无法正常转换引用格式。
Fixes #9453
```release-note
```
> fix(selection): fix missing settings

- .vscode/launch.json
Before this PR: 
- Debug配置未添加.env适配
After this PR:
- 为Debug配置添加envFile属性
> chore(vscode): improve VSCode launch configurations for debugging

- src/renderer/src/assets/styles/selection-toolbar.scss
- src/renderer/src/windows/selection/toolbar/SelectionToolbar.tsx
移除重复定义的颜色变量，统一使用 --color-primary 作为悬停状态的主色
预定义的语义颜色无法同步--color-primary变化
Fixes #9447
```release-note
```
> style(selection-toolbar): use primary color for selection toolbar

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
…dex assignment
Fixes #8687 
用glm 4.5模型测试一下即可
> fix(OpenAIApiClient): 适配glm 4.5 toolcall

- package.json
- src/main/services/CopilotService.ts
…error management
- Consolidated token file path retrieval into a dedicated method for better clarity and maintainability.
- Updated file system operations to ensure directory existence before writing the token file.
- Enhanced error handling during token save and read operations, ensuring robust logging and user feedback.
copilot token file存储在data 目录，会导致不同设备同步后用不了。
After this PR:
copilot toke file存储在homedir/.cherrystudie/config下面，这样每台设备都是不一样的，也不需要进行同步的。
目前是先读取老的(user data目录的）的token file，如果存在就直接用，主要是兼容老版本，这样不会导致用不了。
如果读取不到，就直接返回新路径，这样新用户或者退出重新登录都会使用新目录了。
Fixes #https://github.com/CherryHQ/cherry-studio/issues/9526
If this PR introduces breaking …
> refactor(CopilotService): streamline token file handling and improve error management

- package.json
- src/main/utils/ocr.ts
* Added sharp as a dependency in package.json to enhance image processing capabilities.
* Removed sharp from the devDependencies section.
* Refactored OCR image preprocessing by integrating grayscale and normalization directly into the process, improving overall efficiency.
sharp包在dev，因为sharp里面有dll，会导致打包后的app启动失败。
After this PR:
移到deps，打包后启动不会失败。 还有删除二值化，这个二值化对一些图片的识别很差。
Fixes #
```release-note
```
> fix: add sharp dependency for image processing and improve ocr

- src/main/services/MCPService.ts
fix onprogress error
Before this PR: 
After this PR:
Fixes #9536
NO
NO
```release-note
NONE or "fix onprogress error"
```
> fix: onprogress handler error

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/config/models.ts
- src/renderer/src/types/index.ts
- src/renderer/src/types/sdk.ts
- 支持 [Qwen Flash](https://help.aliyun.com/zh/model-studio/models#qwenflash) 系列模型
- 支持百炼、火山引擎、OpenRouter、硅基流动 调用 DeepSeek v3.1
- 通过白名单确保只有受支持的提供商的v3.1模型能够通过UI控制思维链
Fixes #
```release-note
```
> feat(models): support qwen-flash & deepseek v3.1 (limited)

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/config/providers.ts
- src/renderer/src/services/ModelMessageService.ts
nvidia需要/think显式开启思考
Fixes #9558
```release-note
```
> fix(qwen3): fix qwen3 thinking control by soft command

- src/renderer/src/components/DraggableList/__tests__/DraggableVirtualList.test.tsx
- src/renderer/src/components/DraggableList/index.tsx
- src/renderer/src/components/DraggableList/virtual-list.tsx
- src/renderer/src/components/Popups/SelectModelPopup/popup.tsx
- src/renderer/src/components/Popups/SelectModelPopup/types.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/ja-jp.json
- src/renderer/src/i18n/locales/ru-ru.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/pages/settings/ProviderSettings/index.tsx
- 支持从 SelectModelPopup 直接跳转到服务商设置界面。
- DraggableVirtualList 可以调用滚动。
https://github.com/user-attachments/assets/0bb8fb71-e8e6-45dc-97a7-bd7e449be77a
Related to #9396 
```release-note
```
> feat: goto provider settings from models popup

- src/renderer/src/pages/home/Markdown/Hyperlink.tsx
- src/renderer/src/pages/home/Markdown/Link.tsx
> feat(Link): add hyperlink tooltips

- src/renderer/src/components/ImageViewer.tsx
修复重叠 menu
| BEFORE| AFTER|
|---|---|
|<img width="397" height="332" alt="image" src="https://github.com/user-attachments/assets/5f6b443e-ea07-4ca7-9a82-989d98e3548e" />|<img width="399" height="350" alt="image" src="https://github.com/user-attachments/assets/fc8434af-18dd-4652-bbeb-0d19391a717c" />|
Fixes #9489 
```release-note
```
> fix(ImageViewer): prevent double menu, improve icons

- src/renderer/src/hooks/useAssistant.ts
> fix: useAssistant hook 导致快捷助手渲染问题

- src/renderer/src/pages/settings/MCPSettings/McpServerCard.tsx
使用卡片之后，宽度变小了，tag 溢出行为没有适配
|BEFORE|AFTER|
|---|---|
|<img width="799" height="176" alt="image" src="https://github.com/user-attachments/assets/46441465-1d83-4776-a0ff-66e3f9600035" />|<img width="432" height="193" alt="image" src="https://github.com/user-attachments/assets/b1f41401-6800-4ee6-a142-a1845966a29e" />|
Fixes #
```release-note
```
> fix: mcp tags overflow

- src/main/services/WebviewService.ts
访问 Grok，Claude 小程序的时候会出现 Cloudflare 的人机验证，并且无法通过
After this PR:
可正常通过 Cloudflare 的人机验证
Fixes #8522, fixes #8013, fixes #8338
过去只配置了 `session.setUserAgent`，如果该网页发出其他请求不会遵循新 UA，导致访问 Cloudflare UA 不一致。现在通过配置 `session.webRequest.onBeforeSendHeaders` 拦截该 session 下的每一个 HTTP 请求，使得所有请求的 UA 都设置为新的 UA
```release-note
```
> fix: cloudflare turnstile protection error

- package.json
- src/main/services/SelectionService.ts
- yarn.lock
After this PR:
Fixes #9639 
```release-note
```
> chore: update electron to 37.4.0

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/config/models.ts
After this PR:
Fixes #9685
```release-note
```
> fix: support DeepSeek v3.1 for ppio & openrouter free

- src/renderer/src/pages/notes/HeaderNavbar.tsx
> fix: missing note sidebar control button when the navigation bar is on the left

- scripts/after-pack.js
- scripts/build-npm.js
- Added support for downloading and retaining architecture-specific versions of the `@img/sharp` and `@img/sharp-libvips` packages for macOS, Linux, and Windows platforms.
- Removed the deprecated function for deleting macOS-only packages, streamlining the package management process.
- Updated the `after-pack.js` and `build-npm.js` scripts to ensure proper handling of image processing dependencies across different architectures.
sharp包报错
After this PR: 
不报错，能正常使用。
Fixes #9709  Fixes #9714
This checklist is not enforcing, but it's a reminder of items that …
> feat: enhance package management for image processing libraries

- src/renderer/src/aiCore/clients/openai/OpenAIApiClient.ts
- src/renderer/src/types/sdk.ts
- src/renderer/src/utils/__tests__/naming.test.ts
- src/renderer/src/utils/naming.ts
修改getLowerBaseModelName函数以处理OpenRouter的:free后缀
在OpenAIApiClient中添加enableGenerateImage参数支持图像生成
Fixes #
```release-note
```
> feat(openrouter): support openrouter to generate image

- src/renderer/src/trace/pages/Component.tsx
- src/renderer/src/trace/pages/TraceTree.tsx
- src/renderer/src/trace/pages/index.tsx
fix typo grap gap
After this PR:
Fixes #
```release-note
```
> fix typo grap gap

- electron.vite.config.ts
- yarn.lock
> chore: update vite down to 7.1.5

- src/renderer/src/components/CodeBlockView/view.tsx
- src/renderer/src/components/CodeEditor/index.tsx
- src/renderer/src/components/CodeViewer.tsx
- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
改进 CodeViewer props，用法和 CodeEditor 对齐：
- 增加 `maxHeight`，修复设置 `height` 导致无法滚动的问题
- `expanded` 忽略 `height` 和 `maxHeight`
- 使用 `value` 而不是 `children`
回退 richeditor pr 修改，用 ReactMarkdown 渲染提示词。
Fixes #9783
fixes #9798
```release-note
```
> refactor(CodeViewer): improve props, aligned to CodeEditor

- src/renderer/src/components/CodeBlockView/view.tsx
- src/renderer/src/components/CodeEditor/index.tsx
- src/renderer/src/components/CodeViewer.tsx
- src/renderer/src/components/DraggableList/__tests__/DraggableList.test.tsx
- src/renderer/src/components/DraggableList/__tests__/useDraggableReorder.test.ts
- src/renderer/src/components/DraggableList/list.tsx
- src/renderer/src/components/DraggableList/useDraggableReorder.ts
- src/renderer/src/components/DraggableList/virtual-list.tsx
- src/renderer/src/components/Tab/TabContainer.tsx
- src/renderer/src/components/dnd/Sortable.tsx
- src/renderer/src/components/dnd/useDndReorder.ts
- src/renderer/src/pages/knowledge/items/KnowledgeFiles.tsx
- src/renderer/src/pages/settings/AssistantSettings/AssistantPromptSettings.tsx
- src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
- src/renderer/src/pages/settings/ProviderSettings/ProviderList.tsx
- src/renderer/src/store/tabs.ts
- 修复拖拽列表 Sortable 的 horizontal 样式
- 增加 gap 参数
horizontal 没有设置样式
After this PR:
修复样式
以 Tabs 为例演示：
https://github.com/user-attachments/assets/2efa8ed3-3c1f-4dcc-b4e0-a69a26eca258
Fixes #
```release-note
```
> fix(dnd): horizontal sortable

- src/renderer/src/types/mcp.ts
将联合类型替换为字符串校验并优化 http 相关类型的转换
https://github.com/CherryHQ/cherry-studio/pull/9850#discussion_r2318672258
Fixes #
```release-note
```
> refactor(mcp): use includes http to detect streamable http type mcp server

- .github/workflows/auto-i18n.yml
对fork pr没有权限，ci会报错
Fixes #
```release-note
```
> fix: only allow auto-i18n running on branches in main repo

- src/renderer/src/config/models/default.ts
- src/renderer/src/config/models/reasoning.ts
- src/renderer/src/config/models/websearch.ts
add qwen3-max-preview model support for DashScope provider
https://help.aliyun.com/zh/model-studio/models#b00bc62972qtn
> feat: add qwen3-max-preview model support for DashScope provider

- package.json
- src/renderer/src/components/RichEditor/components/YamlFrontMatterNodeView.tsx
- src/renderer/src/components/RichEditor/extensions/yaml-front-matter.ts
- src/renderer/src/components/RichEditor/useRichEditor.ts
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/utils/__tests__/markdownConverter.test.ts
- src/renderer/src/utils/markdownConverter.ts
- yarn.lock
- Introduced a new plugin to parse and render YAML front matter in markdown documents.
- Updated the markdown converter to handle YAML front matter, preserving its structure during conversion.
- Added corresponding tests to ensure YAML front matter is retained correctly in markdown to HTML and vice versa.
- Enhanced i18n files with new translations for front matter properties in English, Chinese (Simplified and Traditional).
- Included the 'yaml' package as a dependency in package.json.
After this PR:
Fixes #9959 
Test Case:
```
---
tags:
- 你好
aliases:
- "1111"
- "222"
- "333"
- "3333"
cssclasses:
- fffff
- ssss
- s12
- 你好
Author: DeJeune
Date: true
ppp: ffff
---
```
> fix: add YAML front matter support in markdown processing

- src/renderer/src/aiCore/prepareParams/parameterBuilder.ts
- src/renderer/src/aiCore/utils/reasoning.ts
Fixes #9897
错误来源
https://github.com/vercel/ai/blob/c2871e6e845e6e34cdb91e56e350e93a951f5faa/packages/amazon-bedrock/src/bedrock-chat-language-model.ts
> fix: implement Anthropic thinking budget calculation in reasoning logic

- src/renderer/src/components/dnd/ItemRenderer.tsx
- src/renderer/src/components/dnd/Sortable.tsx
- src/renderer/src/components/dnd/SortableItem.tsx
- src/renderer/src/components/dnd/types.ts
- src/renderer/src/components/dnd/utils.ts
- src/renderer/src/pages/settings/MCPSettings/McpServersList.tsx
- 改进 SortableItem props
- 支持自定义 modifiers，用于限制拖拽范围
- 移除不再使用的代码
https://github.com/user-attachments/assets/d3574a88-baeb-4f30-9a93-dc2da2bec12f
Fixes #
```release-note
```
> refactor(Sortable): improve sortable props, support custom modifiers

- src/renderer/src/App.tsx
- src/renderer/src/assets/styles/index.css
fix: https://github.com/CherryHQ/cherry-studio/pull/9973 
主要是heroui集成的问题，heroui需要在顶层加一个provider，但是会增加一个div标签...
> style: update HeroUIProvider dimensions and reset body background color

- src/renderer/src/components/Tab/TabContainer.tsx
- src/renderer/src/components/WindowControls/WindowControls.styled.ts
- src/renderer/src/components/app/Navbar.tsx
- src/renderer/src/pages/home/Navbar.tsx
- src/renderer/src/pages/minapps/MinAppsPage.tsx
- src/renderer/src/pages/settings/DataSettings/DataSettings.tsx
After this PR:
Fixes #
```release-note
```
> fix(Navbar): some bugs in old ui for custom max/min/close menu

- .github/workflows/claude-translator.yml
After this PR:
Fixes #
```release-note
```
> ci(workflow): update github token secret in claude translator workflow

- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/i18n/translate/el-gr.json
- src/renderer/src/i18n/translate/es-es.json
- src/renderer/src/i18n/translate/fr-fr.json
- src/renderer/src/i18n/translate/ja-jp.json
- src/renderer/src/i18n/translate/pt-pt.json
- src/renderer/src/i18n/translate/ru-ru.json
- src/renderer/src/store/index.ts
#10133 forgot to bump it
Fixes #
```release-note
```
> chore(store): bump persisted reducer version to 154

- src/renderer/src/App.tsx
- src/renderer/src/context/HeroUIProvider.tsx
Centralize context providers in a dedicated directory for better organization and maintainability.
Add locale for HeroUIProvider
Fixes #
```release-note
```
> refactor(context): move HeroUIProvider to context directory

- .oxlintrc.json
- .vscode/settings.json
After this PR:
Fixes #
```release-note
```
> fix: ui package env

- package.json
Add --no-errors-on-unmatched flag to biome format commands in lint-staged configuration to prevent errors when no matching files are found
After this PR:
Fixes #
```release-note
```
> chore: update biome format command to ignore unmatched files

- src/renderer/src/pages/home/Chat.tsx
AttachmentButton is used in MessageEditor, which is not wrapped in QuickPanelProvider. This PR wraps MessageEditor using QuickPanelProvider.
After this PR:
Fixes #
```release-note
```
> fix: wrap MessageEditor with QuickPanelProvider

- src/renderer/src/config/providers.ts
- src/renderer/src/pages/settings/ProviderSettings/ProviderSetting.tsx
- src/renderer/src/store/index.ts
- src/renderer/src/store/migrate.ts
- src/renderer/src/utils/index.ts
- Remove trailing slash from Anthropic API base URL
- Add isAnthropicProvider utility function
- Update provider settings to show full endpoint URL for Anthropic
- Add migration to clean up existing Anthropic provider URLs
修复anthropic 404的错误
> Fix Anthropic API URL and add endpoint path handling

- src/renderer/src/services/AssistantService.ts
> fix: update default content in getDefaultTranslateAssistant function

- src/renderer/src/pages/paintings/SiliconPage.tsx
The Siliconflow platform does not support the Qwen-Image series models.
After this PR:
Support for Qwen-Image series models.
fixes CherryHQ/cherry-studio#10212
Fixes #
Temporarily, there is no consideration for the scenario where Qwen-Image-Edit only supports cases with reference images.
```release-note
Add support for the Qwen-Image series models in the Siliconflow.
```
> feat: add Qwen-Image models in the Siliconflow

- src/renderer/src/components/QuickPanel/view.tsx
- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/home/Inputbar/Inputbar.tsx
- src/renderer/src/pages/home/Inputbar/MentionModelsButton.tsx
支持前导空格用来筛选
https://github.com/user-attachments/assets/2c1f8edb-5518-4598-824e-eb2a52ee1b89
fixes: #10251
fixes: #10252
> fix: support leadingspace to avoid normal text

- src/renderer/src/components/Icons/MinAppIcon.tsx
- src/renderer/src/components/Icons/__tests__/__snapshots__/MinAppIcon.test.tsx.snap
- src/renderer/src/components/Tab/TabContainer.tsx
- src/renderer/src/hooks/useMinappPopup.ts
- src/renderer/src/pages/minapps/MinAppPage.tsx
- src/renderer/src/pages/settings/AboutSettings.tsx
- src/renderer/src/pages/settings/DataSettings/JoplinSettings.tsx
- src/renderer/src/pages/settings/DataSettings/NotionSettings.tsx
- src/renderer/src/pages/settings/DataSettings/S3Settings.tsx
- src/renderer/src/pages/settings/DataSettings/SiyuanSettings.tsx
- src/renderer/src/pages/settings/DataSettings/YuqueSettings.tsx
- openMinApp function doesn't work properly
After this PR:
- Adds support for temporary minapps.
- Uses openSmartMinApp with app logo to open documentation sites.
Fixes #10274
> fix(minapps): openMinApp function doesn't work properly

- src/renderer/src/components/Popups/SaveToKnowledgePopup.tsx
- src/renderer/src/pages/notes/NotesPage.tsx
- Add validation for knowledge base configuration before saving
- Enhance error handling for note content reading
- Implement content backup and restoration during file rename
- Add content verification after rename operations
- Improve user feedback with specific error messages
- File rename operations could result in content loss without any warning or recovery mechanism
- Knowledge base saving lacked proper validation, leading to unclear error messages
- No content backup was performed before file operations, making data recovery impossible
- Users received generic error messages that didn't help identify the root cause
After this PR:
- File rename operations now include content backup and verification to prevent data loss
- Knowledge base configuration is validated …
> feat: improve content protection during file operations

- src/renderer/src/config/models/reasoning.ts
correct regex pattern for deepseek v3.1 model detection
Fixes #10406
```release-note
```
> fix(reasoning): correct regex pattern for deepseek model detection

- src/renderer/src/aiCore/tools/KnowledgeSearchTool.ts
- src/renderer/src/aiCore/tools/WebSearchTool.ts
- Updated the descriptions for the knowledgeSearchTool and webSearchTool to provide clearer context on their functionality.
- Improved the formatting of prepared queries and relevant links in the descriptions to enhance user understanding.
- Added information on how to use the tools with additional context for refined searches.
> refactor(tools): enhance descriptions for knowledge and web search tools

- src/renderer/src/i18n/locales/en-us.json
- src/renderer/src/i18n/locales/zh-cn.json
- src/renderer/src/i18n/locales/zh-tw.json
- src/renderer/src/pages/notes/NotesSidebar.tsx
- src/renderer/src/services/ApiService.ts
> feat: allowing notes to be renamed using LLM
